//! Repository-scoped Solo data layout.
//!
//! The source checkout is deliberately not used as a state directory. The
//! default root is `<Forge data root>/solo/<repository-id>/`; `--data-dir`
//! selects that exact root and never silently falls back to the default.

use std::fs::{self, File, OpenOptions};
use std::io::{self, Read, Write};
use std::path::{Component, Path, PathBuf};

use uuid::Uuid;

use crate::repository::SoloIdMarker;

/// Directory name below the configured Forge data root.
pub const SOLO_DATA_DIR_NAME: &str = "solo";
/// Binding file kept with a Solo data root so explicit overrides fail closed
/// instead of selecting a Project by name or creation order.
pub const REPOSITORY_BINDING_FILE: &str = "repository-binding";
/// SQLite database filename used by the ordinary Forge schema.
pub const DATABASE_FILE: &str = "forge.db";
/// Secret material generated by the ordinary Forge configuration layer.
pub const JWT_SECRET_FILE: &str = "jwt_secret.bin";
/// Credential material persisted by the embedded local Agent Runtime.
pub const DAEMON_CREDENTIALS_FILE: &str = "daemon_credentials.json";
/// Lock filename owned by [`crate::runtime_lock::RuntimeLock`].
pub const RUNTIME_LOCK_FILE: &str = "runtime.lock";
const MAX_BINDING_BYTES: u64 = 4096;
const BINDING_RETRY_ATTEMPTS: usize = 12;
const BINDING_RETRY_DELAY: std::time::Duration = std::time::Duration::from_millis(5);

/// All durable paths owned by one Solo data root.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SoloDataPaths {
    pub root: PathBuf,
    pub db_path: PathBuf,
    pub protected_store: PathBuf,
    pub logs: PathBuf,
    pub media: PathBuf,
    pub credentials: PathBuf,
    pub worktrees: PathBuf,
    pub runtime_lock: PathBuf,
    pub repository_binding: PathBuf,
}

impl SoloDataPaths {
    #[must_use]
    pub fn new(root: PathBuf) -> Self {
        Self {
            db_path: root.join(DATABASE_FILE),
            protected_store: root.join("protected"),
            logs: root.join("logs"),
            media: root.join("media"),
            credentials: root.join("credentials"),
            worktrees: root.join("worktrees"),
            runtime_lock: root.join(RUNTIME_LOCK_FILE),
            repository_binding: root.join(REPOSITORY_BINDING_FILE),
            root,
        }
    }

    #[must_use]
    pub fn data_root(&self) -> &Path {
        &self.root
    }

    #[must_use]
    pub fn database_path(&self) -> &Path {
        &self.db_path
    }

    #[must_use]
    pub fn protected_store_path(&self) -> &Path {
        &self.protected_store
    }

    #[must_use]
    pub fn logs_path(&self) -> &Path {
        &self.logs
    }

    #[must_use]
    pub fn media_path(&self) -> &Path {
        &self.media
    }

    #[must_use]
    pub fn credentials_path(&self) -> &Path {
        &self.credentials
    }

    #[must_use]
    pub fn worktrees_path(&self) -> &Path {
        &self.worktrees
    }

    #[must_use]
    pub fn runtime_lock_path(&self) -> &Path {
        &self.runtime_lock
    }

    /// Check an existing root before acquiring the runtime lock or publishing
    /// the repository binding. Missing roots and existing empty private
    /// directories are safe first-run targets; an existing root is otherwise
    /// accepted only when its binding already names `repository_id`.
    pub fn preflight_existing_root(&self, repository_id: Uuid) -> Result<DataRootPreflight> {
        preflight_data_root(&self.root, repository_id)
    }

    /// Create the data root and ordinary state subdirectories, then bind it
    /// to the stable repository identifier. This is the first mutating data
    /// operation and should only be called after terminal preflight and lock
    /// acquisition.
    pub fn ensure_layout(&self, repository_root: &Path, repository_id: Uuid) -> Result<()> {
        validate_outside_repository(&self.root, repository_root)?;
        ensure_private_directory(&self.root)?;
        // Validate or create the binding before creating any child state. An
        // existing explicit root with a mismatched binding must remain
        // completely untouched by this call.
        self.ensure_repository_binding(repository_id)?;
        for directory in [
            &self.protected_store,
            &self.logs,
            &self.media,
            &self.credentials,
            &self.worktrees,
        ] {
            ensure_private_directory(directory)?;
        }
        Ok(())
    }

    /// Ensure an explicit data root is bound to this repository identifier.
    /// Existing mismatches are never replaced.
    pub fn ensure_repository_binding(&self, repository_id: Uuid) -> Result<()> {
        let expected = SoloIdMarker::new(repository_id).encode();
        let path = &self.repository_binding;

        for attempt in 0..=BINDING_RETRY_ATTEMPTS {
            match fs::symlink_metadata(path) {
                Ok(metadata) => {
                    if metadata.file_type().is_symlink() {
                        return Err(DataDirError::BindingSymlink { path: path.clone() });
                    }
                    if !metadata.is_file() {
                        return Err(DataDirError::BindingNotRegular { path: path.clone() });
                    }
                    validate_private_permissions(path)?;
                    let actual = read_binding(path)?;
                    if actual != repository_id {
                        return Err(DataDirError::RepositoryMismatch {
                            path: path.clone(),
                            expected: repository_id,
                            actual,
                        });
                    }
                    return Ok(());
                }
                Err(source) if source.kind() == io::ErrorKind::NotFound => {
                    match write_binding_atomically(&self.root, path, &expected) {
                        Ok(()) => return Ok(()),
                        Err(source)
                            if source.kind() == io::ErrorKind::AlreadyExists
                                && attempt < BINDING_RETRY_ATTEMPTS =>
                        {
                            // Another process won the no-replace publication
                            // race. Re-read its complete binding next.
                            std::thread::sleep(BINDING_RETRY_DELAY);
                        }
                        Err(source) => {
                            return Err(DataDirError::BindingIo {
                                path: path.clone(),
                                source,
                            });
                        }
                    }
                }
                Err(source) => {
                    return Err(DataDirError::BindingIo {
                        path: path.clone(),
                        source,
                    });
                }
            }
        }

        Err(DataDirError::BindingIo {
            path: path.clone(),
            source: io::Error::new(
                io::ErrorKind::WouldBlock,
                "repository binding publication remained contended",
            ),
        })
    }

    /// Read the repository identifier recorded in this data root, if any.
    pub fn read_repository_binding(&self) -> Result<Option<Uuid>> {
        match fs::symlink_metadata(&self.repository_binding) {
            Ok(metadata) => {
                if metadata.file_type().is_symlink() {
                    return Err(DataDirError::BindingSymlink {
                        path: self.repository_binding.clone(),
                    });
                }
                if !metadata.is_file() {
                    return Err(DataDirError::BindingNotRegular {
                        path: self.repository_binding.clone(),
                    });
                }
                validate_private_permissions(&self.repository_binding)?;
                read_binding(&self.repository_binding).map(Some)
            }
            Err(source) if source.kind() == io::ErrorKind::NotFound => Ok(None),
            Err(source) => Err(DataDirError::BindingIo {
                path: self.repository_binding.clone(),
                source,
            }),
        }
    }
}

/// Errors returned while resolving or creating the Solo data root.
#[derive(Debug, thiserror::Error)]
pub enum DataDirError {
    #[error("failed to inspect repository/data path {path}: {source}")]
    Io { path: PathBuf, source: io::Error },

    #[error("Solo data root {data_root} must be outside source worktree {repository_root}")]
    DataRootInsideRepository {
        data_root: PathBuf,
        repository_root: PathBuf,
    },

    #[error("Solo data root is a symlink, which is not allowed: {path}")]
    DataRootSymlink { path: PathBuf },

    #[error("Solo data root is not a directory: {path}")]
    DataRootNotDirectory { path: PathBuf },

    #[error("Solo data root has insecure permissions (must be owner-only): {path}")]
    DataRootPermissions { path: PathBuf },

    #[error(
        "Solo data root {path} is non-empty but has no repository binding; choose an empty directory or an existing bound Solo data root"
    )]
    UnboundNonEmptyDataRoot { path: PathBuf },

    #[error("sensitive Solo data path is a symlink and cannot be followed: {path}")]
    SensitiveLeafSymlink { path: PathBuf },

    #[error("sensitive Solo data path is not a regular file: {path}")]
    SensitiveLeafNotRegular { path: PathBuf },

    #[error("repository binding is a symlink, which is not allowed: {path}")]
    BindingSymlink { path: PathBuf },

    #[error("repository binding is not a regular file: {path}")]
    BindingNotRegular { path: PathBuf },

    #[error("failed to read repository binding {path}: {source}")]
    BindingIo { path: PathBuf, source: io::Error },

    #[error("repository binding is malformed at {path}: {reason}")]
    BindingMalformed { path: PathBuf, reason: String },

    #[error("repository binding has insecure permissions (must be owner-only): {path}")]
    BindingPermissions { path: PathBuf },

    #[error(
        "Solo data root {path} belongs to repository {actual}, not the current repository {expected}"
    )]
    RepositoryMismatch {
        path: PathBuf,
        expected: Uuid,
        actual: Uuid,
    },
}

/// Result type returned by Solo data-root resolution and binding operations.
pub type Result<T> = std::result::Result<T, DataDirError>;

/// Result of checking the root before lock acquisition and binding
/// publication.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DataRootPreflight {
    /// The root does not exist yet and may be created by layout setup.
    Absent,
    /// The root exists, is private, and contains no entries.
    Empty,
    /// The root is already bound to the requested repository identifier.
    Bound,
}

/// Compute the default repository-scoped root under a Forge data directory.
#[must_use]
pub fn default_solo_data_root(forge_data_root: &Path, repository_id: Uuid) -> PathBuf {
    forge_data_root
        .join(SOLO_DATA_DIR_NAME)
        .join(repository_id.to_string())
}

/// Resolve the exact root selected by `--data-dir`, or the configured Forge
/// root's repository-scoped default when the option is absent.
#[must_use]
pub fn resolve_solo_data_root(
    forge_data_root: &Path,
    repository_id: Uuid,
    data_dir_override: Option<&Path>,
) -> PathBuf {
    let root = data_dir_override
        .map(Path::to_path_buf)
        .unwrap_or_else(|| default_solo_data_root(forge_data_root, repository_id));
    absolute_path(
        &root,
        &std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")),
    )
}

/// Resolve paths using `FORGE_DATA_DIR`/the normal Forge default as the parent
/// of `solo/<repository-id>` when no explicit override is supplied.
pub fn resolve_data_paths(
    repository_root: &Path,
    repository_id: Uuid,
    data_dir_override: Option<&Path>,
) -> Result<SoloDataPaths> {
    let forge_data_root = config::data_dir_from_env();
    resolve_data_paths_with_forge_root(
        repository_root,
        repository_id,
        &forge_data_root,
        data_dir_override,
    )
}

/// Resolve and validate the state root against a repository using an explicit
/// Forge data root. The override remains exact (it is not nested again).
pub fn resolve_data_paths_with_forge_root(
    repository_root: &Path,
    repository_id: Uuid,
    forge_data_root: &Path,
    data_dir_override: Option<&Path>,
) -> Result<SoloDataPaths> {
    let current_dir = std::env::current_dir().map_err(|source| DataDirError::Io {
        path: PathBuf::from("."),
        source,
    })?;
    resolve_data_paths_from(
        repository_root,
        repository_id,
        forge_data_root,
        data_dir_override,
        &current_dir,
    )
}

/// Deterministic variant of [`resolve_data_paths_with_forge_root`] for tests
/// and embedders that own the process current-directory choice.
pub fn resolve_data_paths_from(
    repository_root: &Path,
    repository_id: Uuid,
    forge_data_root: &Path,
    data_dir_override: Option<&Path>,
    current_dir: &Path,
) -> Result<SoloDataPaths> {
    let repository_root = canonical_directory(repository_root)?;
    let root = data_dir_override
        .map(Path::to_path_buf)
        .unwrap_or_else(|| default_solo_data_root(forge_data_root, repository_id));
    let root = absolute_path(&root, current_dir);
    reject_symlink_components(&root)?;
    // Keep using the canonical path returned by the containment check. This
    // prevents a symlinked existing ancestor from being re-followed later by
    // `create_dir_all` and makes every child path resolve under one root.
    let root = canonicalize_for_containment(&root)?;
    if root == repository_root || root.starts_with(&repository_root) {
        return Err(DataDirError::DataRootInsideRepository {
            data_root: root,
            repository_root,
        });
    }

    if let Ok(metadata) = fs::symlink_metadata(&root) {
        if metadata.file_type().is_symlink() {
            return Err(DataDirError::DataRootSymlink { path: root });
        }
        if !metadata.is_dir() {
            return Err(DataDirError::DataRootNotDirectory { path: root });
        }
        validate_private_permissions(&root)?;
    }

    Ok(SoloDataPaths::new(root))
}

/// Preflight a resolved data root without creating files or acquiring the
/// process lock. This gate prevents a failed or mistyped `--data-dir` from
/// being treated as a fresh Solo store and then having a binding or lock
/// published over foreign state.
pub fn preflight_data_root(data_root: &Path, repository_id: Uuid) -> Result<DataRootPreflight> {
    let current_dir = std::env::current_dir().map_err(|source| DataDirError::Io {
        path: data_root.to_path_buf(),
        source,
    })?;
    let data_root = absolute_path(data_root, &current_dir);
    reject_symlink_components(&data_root)?;

    let metadata = match fs::symlink_metadata(&data_root) {
        Ok(metadata) => metadata,
        Err(source) if source.kind() == io::ErrorKind::NotFound => {
            return Ok(DataRootPreflight::Absent);
        }
        Err(source) => {
            return Err(DataDirError::Io {
                path: data_root,
                source,
            });
        }
    };
    if metadata.file_type().is_symlink() {
        return Err(DataDirError::DataRootSymlink { path: data_root });
    }
    if !metadata.is_dir() {
        return Err(DataDirError::DataRootNotDirectory { path: data_root });
    }
    validate_private_permissions(&data_root)?;
    validate_sensitive_leaves(&data_root)?;

    let mut entries = fs::read_dir(&data_root).map_err(|source| DataDirError::Io {
        path: data_root.clone(),
        source,
    })?;
    if entries.next().is_none() {
        return Ok(DataRootPreflight::Empty);
    }

    let paths = SoloDataPaths::new(data_root.clone());
    match paths.read_repository_binding()? {
        Some(actual) if actual == repository_id => Ok(DataRootPreflight::Bound),
        Some(actual) => Err(DataDirError::RepositoryMismatch {
            path: paths.repository_binding,
            expected: repository_id,
            actual,
        }),
        None => Err(DataDirError::UnboundNonEmptyDataRoot { path: data_root }),
    }
}

fn read_binding(path: &Path) -> Result<Uuid> {
    let file = File::open(path).map_err(|source| DataDirError::BindingIo {
        path: path.to_path_buf(),
        source,
    })?;
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => {
            return Err(DataDirError::BindingSymlink {
                path: path.to_path_buf(),
            });
        }
        Ok(_) => {}
        Err(source) => {
            return Err(DataDirError::BindingIo {
                path: path.to_path_buf(),
                source,
            });
        }
    }
    let metadata = file.metadata().map_err(|source| DataDirError::BindingIo {
        path: path.to_path_buf(),
        source,
    })?;
    if !metadata.is_file() {
        return Err(DataDirError::BindingNotRegular {
            path: path.to_path_buf(),
        });
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if metadata.permissions().mode() & 0o077 != 0 {
            return Err(DataDirError::BindingPermissions {
                path: path.to_path_buf(),
            });
        }
    }
    let mut bytes = Vec::new();
    file.take(MAX_BINDING_BYTES.saturating_add(1))
        .read_to_end(&mut bytes)
        .map_err(|source| DataDirError::BindingIo {
            path: path.to_path_buf(),
            source,
        })?;
    if bytes.len() as u64 > MAX_BINDING_BYTES {
        return Err(DataDirError::BindingMalformed {
            path: path.to_path_buf(),
            reason: format!("file exceeds {MAX_BINDING_BYTES} bytes"),
        });
    }
    let contents = String::from_utf8(bytes).map_err(|error| DataDirError::BindingMalformed {
        path: path.to_path_buf(),
        reason: format!("binding is not valid UTF-8: {error}"),
    })?;
    let contents = contents.strip_suffix('\n').unwrap_or(&contents);
    let mut lines = contents.split('\n');
    let version = lines.next().unwrap_or_default();
    let repository_id = lines.next().unwrap_or_default();
    if lines.next().is_some() || version != "version = 1" {
        return Err(DataDirError::BindingMalformed {
            path: path.to_path_buf(),
            reason: "expected exactly version and repository_id lines".to_owned(),
        });
    }
    let id = repository_id
        .strip_prefix("repository_id = \"")
        .and_then(|value| value.strip_suffix('"'))
        .ok_or_else(|| DataDirError::BindingMalformed {
            path: path.to_path_buf(),
            reason: "second line must be `repository_id = \"<uuid>\"`".to_owned(),
        })?;
    let parsed = Uuid::parse_str(id).map_err(|error| DataDirError::BindingMalformed {
        path: path.to_path_buf(),
        reason: error.to_string(),
    })?;
    if parsed.is_nil() || parsed.to_string() != id {
        return Err(DataDirError::BindingMalformed {
            path: path.to_path_buf(),
            reason: "repository_id must be a canonical non-nil UUID".to_owned(),
        });
    }
    Ok(parsed)
}

fn canonical_directory(path: &Path) -> Result<PathBuf> {
    let metadata = fs::metadata(path).map_err(|source| DataDirError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    if !metadata.is_dir() {
        return Err(DataDirError::Io {
            path: path.to_path_buf(),
            source: io::Error::new(io::ErrorKind::NotADirectory, "path is not a directory"),
        });
    }
    fs::canonicalize(path).map_err(|source| DataDirError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn canonicalize_for_containment(path: &Path) -> Result<PathBuf> {
    let absolute = if path.is_absolute() {
        path.to_path_buf()
    } else {
        let current_dir = std::env::current_dir().map_err(|source| DataDirError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        current_dir.join(path)
    };

    let mut existing = absolute.clone();
    let mut suffix = Vec::new();
    while fs::symlink_metadata(&existing).is_err() {
        let name = existing
            .file_name()
            .ok_or_else(|| DataDirError::Io {
                path: absolute.clone(),
                source: io::Error::new(io::ErrorKind::NotFound, "no existing parent"),
            })?
            .to_os_string();
        suffix.push(name);
        if !existing.pop() {
            return Err(DataDirError::Io {
                path: absolute,
                source: io::Error::new(io::ErrorKind::NotFound, "no existing parent"),
            });
        }
    }
    let _metadata = fs::symlink_metadata(&existing).map_err(|source| DataDirError::Io {
        path: existing.clone(),
        source,
    })?;
    // Canonicalizing this existing ancestor is intentional: it lets us reject
    // an override that resolves inside the source worktree.
    let mut result = fs::canonicalize(&existing).map_err(|source| DataDirError::Io {
        path: existing,
        source,
    })?;
    for name in suffix.iter().rev() {
        result.push(name);
    }
    Ok(result)
}

/// Reject symlink components before any later path-based creation. `std` does
/// not expose a portable no-follow directory-open API, so this closes the
/// common ancestor-symlink case while callers retain the canonical path.
fn reject_symlink_components(path: &Path) -> Result<()> {
    let mut current = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Prefix(prefix) => current.push(prefix.as_os_str()),
            Component::RootDir => current.push(component.as_os_str()),
            Component::CurDir => {}
            Component::ParentDir => current.push(component.as_os_str()),
            Component::Normal(name) => {
                current.push(name);
                match fs::symlink_metadata(&current) {
                    Ok(metadata)
                        if metadata.file_type().is_symlink()
                            && !is_trusted_platform_alias(&current) =>
                    {
                        return Err(DataDirError::DataRootSymlink { path: current });
                    }
                    Ok(_) => {}
                    Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
                    Err(source) => {
                        return Err(DataDirError::Io {
                            path: current,
                            source,
                        });
                    }
                }
            }
        }
    }
    Ok(())
}

/// macOS exposes several immutable root-owned compatibility aliases as
/// symlinks (notably `/var` -> `/private/var`). Rejecting those would make
/// ordinary system temporary directories unusable while providing no
/// user-controlled redirection. All other symlink components still fail
/// closed.
fn is_trusted_platform_alias(path: &Path) -> bool {
    #[cfg(target_os = "macos")]
    {
        matches!(path.to_str(), Some("/var" | "/tmp" | "/etc"))
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = path;
        false
    }
}

/// Inspect fixed sensitive paths using `symlink_metadata` only. In
/// particular, do not open a credential or secret path while deciding whether
/// the root is safe to use.
fn validate_sensitive_leaves(root: &Path) -> Result<()> {
    for path in [root.join(DATABASE_FILE), root.join(JWT_SECRET_FILE)] {
        validate_sensitive_leaf(&path)?;
    }

    let credentials_dir = root.join("credentials");
    match fs::symlink_metadata(&credentials_dir) {
        Ok(metadata) if metadata.file_type().is_symlink() => {
            Err(DataDirError::SensitiveLeafSymlink {
                path: credentials_dir,
            })
        }
        Ok(metadata) if !metadata.is_dir() => Err(DataDirError::SensitiveLeafNotRegular {
            path: credentials_dir,
        }),
        Ok(_) => validate_sensitive_leaf(&credentials_dir.join(DAEMON_CREDENTIALS_FILE)),
        Err(source) if source.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(source) => Err(DataDirError::Io {
            path: credentials_dir,
            source,
        }),
    }
}

fn validate_sensitive_leaf(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => {
            Err(DataDirError::SensitiveLeafSymlink {
                path: path.to_path_buf(),
            })
        }
        Ok(metadata) if !metadata.is_file() => Err(DataDirError::SensitiveLeafNotRegular {
            path: path.to_path_buf(),
        }),
        Ok(_) => Ok(()),
        Err(source) if source.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(source) => Err(DataDirError::Io {
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn absolute_path(path: &Path, current_dir: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        current_dir.join(path)
    }
}

fn ensure_private_directory(path: &Path) -> Result<()> {
    reject_symlink_components(path)?;
    match fs::symlink_metadata(path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() {
                return Err(DataDirError::DataRootSymlink {
                    path: path.to_path_buf(),
                });
            }
            if !metadata.is_dir() {
                return Err(DataDirError::DataRootNotDirectory {
                    path: path.to_path_buf(),
                });
            }
            validate_private_permissions(path)
        }
        Err(source) if source.kind() == io::ErrorKind::NotFound => {
            fs::create_dir_all(path).map_err(|source| DataDirError::Io {
                path: path.to_path_buf(),
                source,
            })?;
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                fs::set_permissions(path, fs::Permissions::from_mode(0o700)).map_err(|source| {
                    DataDirError::Io {
                        path: path.to_path_buf(),
                        source,
                    }
                })?;
            }
            Ok(())
        }
        Err(source) => Err(DataDirError::Io {
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn validate_outside_repository(data_root: &Path, repository_root: &Path) -> Result<()> {
    let repository_root = canonical_directory(repository_root)?;
    let data_root_for_check = canonicalize_for_containment(data_root)?;
    if data_root_for_check == repository_root || data_root_for_check.starts_with(&repository_root) {
        return Err(DataDirError::DataRootInsideRepository {
            data_root: data_root.to_path_buf(),
            repository_root,
        });
    }
    Ok(())
}

fn write_binding_atomically(root: &Path, path: &Path, contents: &str) -> io::Result<()> {
    let temporary_path = root.join(format!(".{REPOSITORY_BINDING_FILE}.{}.tmp", Uuid::new_v4()));
    let result = (|| {
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        std::os::unix::fs::OpenOptionsExt::mode(&mut options, 0o600);

        let mut file = options.open(&temporary_path)?;
        file.write_all(contents.as_bytes())?;
        file.sync_all()?;
        set_private_permissions(&file)?;
        file.sync_all()?;
        drop(file);

        // Hard-link publication is atomic and never replaces a binding
        // created by another process.
        fs::hard_link(&temporary_path, path)?;
        sync_directory(root)
    })();

    match result {
        Ok(()) => fs::remove_file(&temporary_path),
        Err(error) => {
            let _ = fs::remove_file(&temporary_path);
            Err(error)
        }
    }
}

fn validate_private_permissions(path: &Path) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let metadata = fs::symlink_metadata(path).map_err(|source| DataDirError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        if metadata.permissions().mode() & 0o077 != 0 {
            let is_binding = path
                .file_name()
                .is_some_and(|name| name == REPOSITORY_BINDING_FILE);
            if is_binding {
                return Err(DataDirError::BindingPermissions {
                    path: path.to_path_buf(),
                });
            }
            return Err(DataDirError::DataRootPermissions {
                path: path.to_path_buf(),
            });
        }
    }
    Ok(())
}

fn set_private_permissions(file: &File) -> io::Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        file.set_permissions(fs::Permissions::from_mode(0o600))?;
    }
    Ok(())
}

fn sync_directory(path: &Path) -> io::Result<()> {
    #[cfg(unix)]
    {
        File::open(path).and_then(|file| file.sync_all())?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::repository::SoloIdMarker;
    use tempfile::TempDir;

    fn id() -> Uuid {
        Uuid::parse_str("00000000-0000-4000-8000-000000000001").unwrap()
    }

    fn repository(root: &TempDir) -> PathBuf {
        let path = root.path().join("repository");
        fs::create_dir(&path).unwrap();
        path
    }

    #[test]
    fn default_root_is_repository_scoped_and_exact_override_is_not_nested() {
        let forge_root = Path::new("/tmp/forge");
        assert_eq!(
            default_solo_data_root(forge_root, id()),
            PathBuf::from("/tmp/forge/solo/00000000-0000-4000-8000-000000000001")
        );
        assert_eq!(
            resolve_solo_data_root(forge_root, id(), Some(Path::new("/tmp/custom"))),
            PathBuf::from("/tmp/custom")
        );
    }

    #[test]
    fn source_worktree_never_contains_resolved_data_root() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let forge_root = outer.path().join("forge");
        let paths =
            resolve_data_paths_from(&source, id(), &forge_root, None, Path::new("/tmp")).unwrap();
        assert!(!paths.root.starts_with(&source));
        assert!(paths
            .root
            .starts_with(fs::canonicalize(outer.path()).unwrap().join("forge")));
    }

    #[test]
    fn preflight_accepts_absent_root_without_creating_it() {
        let outer = TempDir::new().unwrap();
        let root = outer.path().join("new-state");
        assert_eq!(
            preflight_data_root(&root, id()).unwrap(),
            DataRootPreflight::Absent
        );
        assert!(!root.exists());
    }

    #[test]
    fn preflight_accepts_existing_empty_private_root() {
        let outer = TempDir::new().unwrap();
        let root = outer.path().join("empty-state");
        fs::create_dir(&root).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        }
        assert_eq!(
            preflight_data_root(&root, id()).unwrap(),
            DataRootPreflight::Empty
        );
    }

    #[test]
    fn preflight_rejects_nonempty_unbound_root_including_foreign_state_files() {
        let outer = TempDir::new().unwrap();
        let root = outer.path().join("unbound-state");
        fs::create_dir(&root).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        }

        for filename in [DATABASE_FILE, RUNTIME_LOCK_FILE] {
            fs::write(root.join(filename), b"foreign state").unwrap();
            let error = preflight_data_root(&root, id())
                .expect_err("unbound non-empty roots must fail closed");
            assert!(matches!(
                error,
                DataDirError::UnboundNonEmptyDataRoot { .. }
            ));
            fs::remove_file(root.join(filename)).unwrap();
        }
    }

    #[test]
    fn preflight_accepts_nonempty_root_only_when_binding_matches() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let root = outer.path().join("bound-state");
        fs::create_dir(&root).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        }
        let paths =
            resolve_data_paths_with_forge_root(&source, id(), outer.path(), Some(&root)).unwrap();
        paths.ensure_layout(&source, id()).unwrap();
        fs::write(&paths.db_path, b"database").unwrap();
        assert_eq!(
            paths.preflight_existing_root(id()).unwrap(),
            DataRootPreflight::Bound
        );
    }

    #[test]
    fn override_inside_source_is_rejected() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let override_dir = source.join(".solo-state");
        let error = resolve_data_paths_from(
            &source,
            id(),
            outer.path(),
            Some(&override_dir),
            Path::new("/tmp"),
        )
        .expect_err("state under source must fail");
        assert!(matches!(
            error,
            DataDirError::DataRootInsideRepository { .. }
        ));
    }

    #[test]
    fn layout_is_private_and_binding_is_idempotent() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let paths = resolve_data_paths_with_forge_root(&source, id(), outer.path(), None).unwrap();
        paths.ensure_layout(&source, id()).unwrap();
        paths.ensure_layout(&source, id()).unwrap();
        assert!(paths.db_path.ends_with("forge.db"));
        assert!(paths.logs.is_dir());
        assert!(paths.media.is_dir());
        assert_eq!(paths.read_repository_binding().unwrap(), Some(id()));
        assert_eq!(
            fs::read_to_string(&paths.repository_binding).unwrap(),
            SoloIdMarker::new(id()).encode()
        );
        assert_eq!(
            fs::read_dir(&paths.root)
                .unwrap()
                .filter_map(std::result::Result::ok)
                .filter(|entry| {
                    let name = entry.file_name();
                    let name = name.to_string_lossy();
                    name.starts_with(".repository-binding.") && name.ends_with(".tmp")
                })
                .count(),
            0
        );
    }

    #[test]
    fn mismatched_binding_fails_closed() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let paths = resolve_data_paths_with_forge_root(&source, id(), outer.path(), None).unwrap();
        paths.ensure_layout(&source, id()).unwrap();
        let other = Uuid::parse_str("00000000-0000-4000-8000-000000000002").unwrap();
        fs::write(&paths.repository_binding, SoloIdMarker::new(other).encode()).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&paths.repository_binding, fs::Permissions::from_mode(0o600))
                .unwrap();
        }
        let error = paths
            .ensure_repository_binding(id())
            .expect_err("mismatched root must fail");
        assert!(matches!(error, DataDirError::RepositoryMismatch { .. }));
    }

    #[test]
    fn malformed_empty_binding_is_rejected_without_panicking() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let paths = resolve_data_paths_with_forge_root(&source, id(), outer.path(), None).unwrap();
        paths.ensure_layout(&source, id()).unwrap();
        fs::write(
            &paths.repository_binding,
            "version = 1\nrepository_id = \"\"\n",
        )
        .unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&paths.repository_binding, fs::Permissions::from_mode(0o600))
                .unwrap();
        }
        let error = paths
            .read_repository_binding()
            .expect_err("empty binding must be malformed");
        assert!(matches!(error, DataDirError::BindingMalformed { .. }));
    }

    #[cfg(unix)]
    #[test]
    fn preflight_rejects_symlinked_sensitive_leaves_without_following_them() {
        use std::os::unix::fs::PermissionsExt;

        let outer = TempDir::new().unwrap();
        let root = outer.path().join("state");
        fs::create_dir(&root).unwrap();
        fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        let target = outer.path().join("foreign-secret");
        fs::write(&target, b"must remain untouched").unwrap();
        std::os::unix::fs::symlink(&target, root.join(JWT_SECRET_FILE)).unwrap();

        let error = preflight_data_root(&root, id()).expect_err("secret symlink");
        assert!(matches!(error, DataDirError::SensitiveLeafSymlink { .. }));
        assert_eq!(fs::read(&target).unwrap(), b"must remain untouched");
    }

    #[cfg(unix)]
    #[test]
    fn preflight_rejects_nonregular_sensitive_leaves() {
        use std::os::unix::fs::PermissionsExt;

        let outer = TempDir::new().unwrap();
        let root = outer.path().join("state");
        fs::create_dir(&root).unwrap();
        fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        fs::create_dir(root.join(DATABASE_FILE)).unwrap();

        let error = preflight_data_root(&root, id()).expect_err("database directory");
        assert!(matches!(
            error,
            DataDirError::SensitiveLeafNotRegular { .. }
        ));
    }

    #[cfg(unix)]
    #[test]
    fn preflight_rejects_symlinked_credentials_directory_or_leaf() {
        use std::os::unix::fs::PermissionsExt;

        let outer = TempDir::new().unwrap();
        let root = outer.path().join("state");
        fs::create_dir(&root).unwrap();
        fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        let target = outer.path().join("foreign-credentials");
        fs::create_dir(&target).unwrap();
        std::os::unix::fs::symlink(&target, root.join("credentials")).unwrap();

        let error = preflight_data_root(&root, id()).expect_err("credentials symlink");
        assert!(matches!(error, DataDirError::SensitiveLeafSymlink { .. }));
    }

    #[test]
    fn mismatched_existing_binding_is_checked_before_child_creation() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let data_root = outer.path().join("state");
        fs::create_dir(&data_root).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&data_root, fs::Permissions::from_mode(0o700)).unwrap();
        }
        let paths =
            resolve_data_paths_with_forge_root(&source, id(), outer.path(), Some(&data_root))
                .unwrap();
        let other = Uuid::parse_str("00000000-0000-4000-8000-000000000002").unwrap();
        fs::write(&paths.repository_binding, SoloIdMarker::new(other).encode()).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&paths.repository_binding, fs::Permissions::from_mode(0o600))
                .unwrap();
        }

        let error = paths
            .ensure_layout(&source, id())
            .expect_err("mismatched binding must fail before child creation");
        assert!(matches!(error, DataDirError::RepositoryMismatch { .. }));
        assert!(!paths.protected_store.exists());
        assert!(!paths.logs.exists());
        assert!(!paths.media.exists());
        assert!(!paths.credentials.exists());
        assert!(!paths.worktrees.exists());
    }

    #[cfg(unix)]
    #[test]
    fn symlink_override_is_rejected() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let target = outer.path().join("outside");
        fs::create_dir(&target).unwrap();
        let link = outer.path().join("link");
        std::os::unix::fs::symlink(&target, &link).unwrap();
        let error = resolve_data_paths_with_forge_root(&source, id(), outer.path(), Some(&link))
            .expect_err("symlink root must fail");
        assert!(matches!(error, DataDirError::DataRootSymlink { .. }));
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_ancestor_override_is_rejected() {
        let outer = TempDir::new().unwrap();
        let source = repository(&outer);
        let target = outer.path().join("outside");
        fs::create_dir(&target).unwrap();
        let link = outer.path().join("link");
        std::os::unix::fs::symlink(&target, &link).unwrap();
        let override_dir = link.join("state");
        let error =
            resolve_data_paths_with_forge_root(&source, id(), outer.path(), Some(&override_dir))
                .expect_err("symlinked ancestor must fail closed");
        assert!(matches!(error, DataDirError::DataRootSymlink { .. }));
    }
}
