[package]
name = "check-executor"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
api-types = { path = "../api-types" }
executors = { path = "../executors" }
git = { path = "../git" }
process-supervisor = { path = "../process-supervisor" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
serde_json = "1"
tempfile = "3"
tokio = { version = "1", features = ["fs", "io-util", "macros", "process", "sync", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }

[lints]
workspace = true
