// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyticsWindow } from "./AnalyticsWindow";
import type { ProjectUsageBreakdown } from "./ProjectUsageBreakdown";
import type { UsageAnalytics } from "./UsageAnalytics";

/**
 * Account-scoped usage analytics across every product surface.
 */
export type AccountUsageAnalyticsResponse = { window: AnalyticsWindow, token_usage: UsageAnalytics, by_project: Array<ProjectUsageBreakdown>, };
