// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingAdjustmentSource } from './PricingAdjustmentSource'
import type { PricingResolutionStatus } from './PricingResolutionStatus'
import type { PricingSettings } from './PricingSettings'
import type { RateBuckets } from './RateBuckets'

/**
 * An agent's pricing: its own adjustment, the one it inherits, and the
 * price Forge would freeze for its next run.
 */
export type AgentPricing = {
  agent_id: string
  runtime_model: string | null
  /**
   * The agent's own adjustment, `null` when it inherits.
   */
  settings: PricingSettings | null
  /**
   * The adjustment on the agent's provider entry or CLI runtime.
   */
  provider_settings: PricingSettings | null
  source: PricingAdjustmentSource
  status: PricingResolutionStatus
  catalog_provider_id: string | null
  catalog_model_id: string | null
  /**
   * models.dev list rates for the matched row.
   */
  catalog_rates: RateBuckets | null
  /**
   * Rates after the adjustment; what the next run is estimated with.
   */
  effective_rates: RateBuckets | null
  /**
   * models.dev providers listing the model when `status` is `ambiguous`.
   */
  candidate_providers: Array<string>
}
