// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentChatTopicPrincipalType } from "./AgentChatTopicPrincipalType";

/**
 * One durable Main Chat topic (D21). A topic is a context epoch *inside*
 * the one account Main Chat -- it is never a second chat, binding, or
 * authority scope. `starting_message_sequence` is the sequence of the
 * visible divider message that opens it; a new Main turn's episodic context
 * is bounded to messages at or after this value in the current topic.
 */
export type AgentChatTopicResponse = { id: string, chat_id: string, sequence: bigint, label: string, summary: string | null, starting_message_id: string | null, starting_message_sequence: bigint, principal_type: AgentChatTopicPrincipalType, principal_id: string | null, created_at: string, 
/**
 * True for exactly one topic per chat: the most recently started one.
 */
is_current: boolean, };
