// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInquiryStatus } from "./AgentInquiryStatus";
import type { AgentInquiryTokenUsage } from "./AgentInquiryTokenUsage";

/**
 * `owner_user_id`, `identity_id`, and `workspace_path` are deliberately not
 * part of this response: internal, not part of the public surface.
 */
export type AgentInquiryResponse = { id: string, chat_id: string, title: string, question: string, status: AgentInquiryStatus, findings: string | null, findings_path: string | null, error: string | null, token_usage: AgentInquiryTokenUsage, duration_ms: bigint | null, version: bigint, created_at: string, started_at: string, finished_at: string | null, };
