// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who started a Main Chat topic. `System` is used only for the migration
 * backfill's one initial topic per existing Main Chat; every topic a user
 * starts from the product is `User`.
 */
export type AgentChatTopicPrincipalType = "user" | "system";
