// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { UsageAggregate } from "./UsageAggregate";

export type AgentResponse = { id: string, name: string, description: string | null, profile_id: string, backend_kind: string, executor_type: string, provider: string | null, model: string | null, reasoning_effort: string | null, permission_policy: string | null, prompt_template: string | null, capabilities: Array<string>, config_json: Record<string, unknown>, credential_handle_id: string | null, daemon_id: string | null, max_concurrent_tasks: bigint, status: AgentStatus, active_task_count: bigint | null, effective_status: string | null, avg_duration_ms: bigint | null, success_rate: number | null, usage: UsageAggregate, is_default: boolean, paused: boolean, owner_id: string | null, visibility: string, version: bigint, created_at: string, updated_at: string, };
