// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors `agent_host::AgentTurnOutput`. The four counters are DISJOINT —
 * context size is `input_tokens + cache_read_tokens + cache_write_tokens`.
 * Never sum them into one "input" number.
 */
export type AgentInquiryTokenUsage = { input_tokens: bigint, output_tokens: bigint, cache_read_tokens: bigint, cache_write_tokens: bigint, };
