// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MutationEnvelope } from "./MutationEnvelope";

/**
 * "Approve plan and start work" (D18, F13): the one atomic, replay-exact
 * command for the proposed-baseline approval gesture. It binds the exact
 * revision/content/render identities the user reviewed and, unlike
 * [`ApproveExecutionBaselineRequest`] followed by
 * [`ActivateExecutionBaselineRequest`], commits approval and activation in
 * a single server transaction under one idempotency key. The web must reuse
 * the same `mutation.idempotency_key` across retries of this exact click so
 * a lost response replays the committed outcome instead of surfacing a
 * false failure.
 */
export type ApproveAndActivateExecutionBaselineRequest = { mutation: MutationEnvelope, revision_id: string, content_digest: string, render_digest: string,
/**
 * Exact baseline version observed while the user reviewed the proposed
 * revision. `mutation.expected_version` is the Project version CAS, the
 * same convention [`ActivateExecutionBaselineRequest`] uses.
 */
expected_baseline_version: bigint, };
