// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionBaselineResponse } from "./ExecutionBaselineResponse";

/**
 * Response for [`ApproveAndActivateExecutionBaselineRequest`] (D18, F13).
 *
 * The identity fields are always populated once the command has committed:
 * they are reconstructed from the frozen command receipt, never re-derived
 * from mutable current state, so the caller can trust `revision_id` is now
 * the Project's active revision even if nothing else in this response could
 * be assembled. `projection` is the full baseline view for rendering; if
 * re-reading it after a successful commit fails, `projection` is absent and
 * `refresh_required` is `true` instead of the whole response failing -- a
 * commit-truthful adapter never turns a successful write into a reported
 * failure because a subsequent read could not be assembled.
 */
export type ApproveAndActivateExecutionBaselineResponse = { baseline_id: string, revision_id: string, approval_id: string, content_digest: string, render_digest: string, projection: ExecutionBaselineResponse | null, refresh_required: boolean, };
