// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed identity and concurrency information for an approval proposal.
 * Command-specific immutable payloads belong in `result`, not in an
 * unbounded field on this envelope.
 */
export type ApprovalTarget = { target_type: string, target_id: string, operation: string | null, version: bigint | null, revision_id: string | null, revision: bigint | null, content_digest: string | null, rendered_digest: string | null, requires_user_authorization: boolean, };
