// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutcomeScopeType } from "./OutcomeScopeType";

/**
 * Canonical scope reference included in every outcome, including failures.
 */
export type CanonicalScopeRef = { scope_type: OutcomeScopeType, scope_id: string, };
