// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CI-step execution counts and timing analytics.
 */
export type CiStepAnalytics = { command: string, total_runs: number, pass_count: number, fail_count: number, success_rate: number, avg_duration_ms: number | null, p50_duration_ms: number | null, p95_duration_ms: number | null, last_run_at: string | null, };
