// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the singular Project Agent chat can admit a turn. This is kept
 * independent from repository and Task-role setup.
 */
export type CoordinationState = "setup_required" | "ready" | "unavailable";
