// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostCoverage } from "./CostCoverage";
import type { CostKind } from "./CostKind";
import type { CostSourceRef } from "./CostSourceRef";
import type { MoneyAmount } from "./MoneyAmount";
import type { UsageCostCoverage } from "./UsageCostCoverage";

/**
 * One normalized summary of reported/estimated money and its coverage.
 */
export type CostSummary = { kind: CostKind, coverage: CostCoverage, provider_reported: MoneyAmount | null, estimated: MoneyAmount | null, known_subtotal: MoneyAmount | null, complete_total: MoneyAmount | null, usage_coverage: UsageCostCoverage, sources: Array<CostSourceRef>, };
