// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostSummary } from "./CostSummary";

/**
 * Preview of an explicit retrospective estimate against one snapshot.
 */
export type CostEstimationPreview = { id: string, project_id: string, snapshot_id: string, usage_set_digest: string, eligible_event_count: number, unmatched_event_count: number, already_reported_event_count: number, projected_cost: CostSummary, expires_at: string, };
