// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostEstimationRunStatus } from "./CostEstimationRunStatus";
import type { CostSummary } from "./CostSummary";

/**
 * Durable result/provenance of a retrospective estimation run.
 */
export type CostEstimationRun = { id: string, project_id: string, preview_id: string, snapshot_id: string, usage_set_digest: string, status: CostEstimationRunStatus, applied_event_count: number, unmatched_event_count: number, cost: CostSummary, created_at: string, };
