// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of a retrospective estimation run.
 */
export type CostEstimationRunStatus = "pending" | "committed" | "failed" | "conflicted" | "superseded";
