// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionBaselineContent } from "./ExecutionBaselineContent";
import type { ExecutionBaselineWriteOperation } from "./ExecutionBaselineWriteOperation";
import type { MutationEnvelope } from "./MutationEnvelope";
import type { RevisionProvenance } from "./RevisionProvenance";

export type CreateExecutionBaselineRequest = { mutation: MutationEnvelope, 
/**
 * The collection endpoint creates only a first `draft`; `propose_for_approval`
 * is rejected there because proposal always targets an existing baseline.
 */
operation: ExecutionBaselineWriteOperation, base_revision_id: string | null, content: ExecutionBaselineContent, rendered_view: string, render_version: string, content_digest: string, render_digest: string, provenance: RevisionProvenance, };
