// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Commit one exact, immutable retrospective preview.
 */
export type CreateCostEstimationRunRequest = { preview_id: string, usage_set_digest: string, idempotency_key: string, };
