// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The command-stream handshake sent by a daemon immediately after an
 * authenticated connection is established. A server may dispatch work only
 * after the advertised revision and required capabilities are accepted.
 */
export type DaemonHandshakeNotification = { protocol_revision: number, capabilities: Array<string>, };
