// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remove a pricing adjustment, falling back to its parent.
 */
export type DeletePricingSettingsQuery = { version: number }
