// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A host file or directory kept out of git (licensed art, model weights,
 * fixtures) that every worktree needs. Copied only when `target` is absent,
 * so a tracked or already-present path is never overwritten.
 */
export type EnvironmentAsset = { 
/**
 * Absolute path on the Forge host.
 */
source: string, 
/**
 * Path relative to the worktree root.
 */
target: string, };
