// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteExecutionFailureClass } from "./RemoteExecutionFailureClass";
import type { RemoteResolvedCandidate } from "./RemoteResolvedCandidate";
import type { RemoteRouteAttempt } from "./RemoteRouteAttempt";
import type { RemoteUsageReport } from "./RemoteUsageReport";

export type ExecutionTerminalNotification = { terminal_report_id: string, execution_id: string, exit_code: number | null, signal: string | null, error: string | null, ts: string, status: string | null, agent_session_id: string | null, summary: string | null, after_sha: string | null, usage_reports: Array<RemoteUsageReport>, failure_class: RemoteExecutionFailureClass | null, retry_at: string | null, resolved_candidate: RemoteResolvedCandidate | null, route_attempts: Array<RemoteRouteAttempt> | null, };
