// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Missing facts are unsupported, including an executor absent from the map.
 */
export type ExecutorAdapterCapabilityFacts = { structured_events: boolean, usage: boolean, resume: boolean, cancel_ack: boolean, terminal_observed: boolean, };
