// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The baseline gate is separate from execution setup.  A ready setup does
 * not imply that an approved baseline is active.
 */
export type ExecutionGate = "pre_baseline_read_only" | "baseline_approval_required" | "active" | "reconciliation_required" | "unavailable";
