// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a blocker widens the whole Project's execution gate or attaches
 * only to the named affected record(s) (D16). Only a Project-wide
 * governing-truth conflict may take the `Project` scope; a Task-,
 * plan-item-, or milestone-scoped conflict must never widen the Project
 * gate for unrelated work.
 */
export type ExecutionBlockerScope = "project" | "task" | "plan_item" | "milestone";
