// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionBlockerCode } from "./ExecutionBlockerCode";
import type { ExecutionBlockerPrincipal } from "./ExecutionBlockerPrincipal";
import type { ExecutionBlockerRecordRef } from "./ExecutionBlockerRecordRef";
import type { ExecutionBlockerScope } from "./ExecutionBlockerScope";
import type { ExecutionBlockerStage } from "./ExecutionBlockerStage";
import type { ExecutionEvidenceSummary } from "./ExecutionEvidenceSummary";
import type { RetryAction } from "./RetryAction";

/**
 * One server-owned execution blocker (D17). Every surface that explains why
 * execution cannot proceed — Project execution setup, Task detail/banner,
 * chat context, phase controls, dispatcher logs, and activity history —
 * renders exactly this projection. Surfaces may adapt layout but must not
 * reinterpret the blocker: exactly one `next_action` is ever offered for
 * it, and Cancel (when applicable) is a separate, always-available Task
 * control rather than a second gate-recovery option.
 */
export type ExecutionBlockerProjection = { code: ExecutionBlockerCode, stage: ExecutionBlockerStage, scope: ExecutionBlockerScope, 
/**
 * The exact record(s) this blocker attaches to. For `scope: project`
 * this is empty or names the Project itself; for a scoped blocker it
 * names exactly the affected Task/plan item/milestone.
 */
affected_refs: Array<ExecutionBlockerRecordRef>, 
/**
 * The authoritative record this blocker is measured against (for
 * example the governing execution-baseline revision).
 */
governing_ref: ExecutionBlockerRecordRef | null, headline: string, safe_explanation: string, 
/**
 * Present only when the blocker is scoped to (or evaluated against) a
 * specific Task's own attempt/commit history.
 */
evidence: ExecutionEvidenceSummary | null, required_principal: ExecutionBlockerPrincipal, 
/**
 * Exactly one permitted next action. A phase control must never offer a
 * second option that only re-enters this same blocker.
 */
next_action: RetryAction, blocker_digest: string, observed_version: bigint, };
