// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionProgress } from "./ExecutionProgress";

/**
 * Canonical execution evidence for one Task, shared by every progress-
 * language surface so a committed result can never regress to "not
 * started" copy on a different screen (F12).
 */
export type ExecutionEvidenceSummary = { attempt_count: bigint, execution_count: bigint, has_commit: boolean, latest_commit_sha: string | null, progress: ExecutionProgress,
/**
 * The exact canonical phrase for `progress`. Surfaces render this
 * string directly instead of re-deriving their own from `progress` or
 * from unrelated Task/gate state.
 */
progress_label: string, };
