// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Define -> Plan -> Build -> Review -> Release stage a blocker belongs
 * to. This is navigation/explanation only; it is never a second workflow or
 * authority store (D17).
 */
export type ExecutionBlockerStage = "define" | "plan" | "build" | "review" | "release";
