// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data-preserving diagnosis for a historical current revision that cannot
 * be represented by the closed execution-baseline schema. The immutable
 * revision remains stored; `successor_revision_id` is a non-authoritative
 * correction draft until an explicit user approval and reconciliation.
 */
export type ExecutionBaselineIntegrityIssue = { revision_id: string, baseline_id: string, field_path: string, invalid_values: Array<string>, diagnostic: string, successor_revision_id: string | null, conflict_id: string | null, reconciliation_id: string | null, };
