// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy baseline/reconciliation projection retained for traceability UI.
 * Charter-backed Task execution reports `Active`; baseline approval is not
 * an execution gate.
 */
export type ExecutionGate = "pre_baseline_read_only" | "baseline_approval_required" | "active" | "reconciliation_required" | "unavailable";
