// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server acknowledgement for a durable terminal notification. The
 * acknowledgement is a request because the daemon must return a response so
 * transport failures cannot be mistaken for a durable delete.
 */
export type ExecutionTerminalAckParams = { terminal_report_id: string, execution_id: string, };
