// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server acknowledgement for any durable daemon journal entry. The
 * acknowledgement is a request because the daemon must return a response so
 * transport failures cannot be mistaken for a durable delete.
 */
export type JournalAckParams = { entry_id: string, };
