// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalTarget } from "./ApprovalTarget";
import type { CanonicalScopeRef } from "./CanonicalScopeRef";
import type { CurrentVersionOrRevision } from "./CurrentVersionOrRevision";
import type { OutcomeCode } from "./OutcomeCode";
import type { OutcomeStatus } from "./OutcomeStatus";
import type { RetryInstruction } from "./RetryInstruction";
import type { SetupRequirement } from "./SetupRequirement";

/**
 * Shared native/MCP model-facing orchestration result.
 */
export type OrchestrationOutcome = { code: OutcomeCode, status: OutcomeStatus, operation: string, scope: CanonicalScopeRef, result: unknown | null, approval_target: ApprovalTarget | null, setup_requirements: Array<SetupRequirement> | null, current_version_or_revision: CurrentVersionOrRevision | null, retry: RetryInstruction | null, safe_message: string, correlation_id: string, replayed: boolean, receipt_id: string | null, event_id: string | null, };
