// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Project and half-open time-window scope for an outcome metric.
 */
export type OutcomeCostScope = { project_id: string, from: string | null, to: string | null, };
