// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoneyAmount } from "./MoneyAmount";
import type { OutcomeCostScope } from "./OutcomeCostScope";
import type { OutcomeEligibility } from "./OutcomeEligibility";
import type { OutcomeIneligibilityReason } from "./OutcomeIneligibilityReason";
import type { OutcomeKind } from "./OutcomeKind";

/**
 * Cost per successful immutable released-milestone snapshot.
 */
export type OutcomeCostMetric = { outcome_kind: OutcomeKind, numerator: MoneyAmount | null, denominator: number, amount_per_outcome: MoneyAmount | null, scope: OutcomeCostScope, eligibility: OutcomeEligibility, ineligibility_reason: OutcomeIneligibilityReason | null, };
