// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a released-milestone outcome metric is not eligible.
 */
export type OutcomeIneligibilityReason = "no_released_milestones" | "no_usage_cost" | "cost_pending" | "cost_partial" | "cost_unavailable";
