// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The exact REST route and method a pending-candidate action posts to.
 * Every surface renders this rather than hand-building the candidate
 * route.
 */
export type PendingDecisionActionTarget = { method: string, path: string, };
