// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionClass } from "./DecisionClass";
import type { DecisionEditorState } from "./DecisionEditorState";
import type { PendingDecisionActionTarget } from "./PendingDecisionActionTarget";
import type { PendingDecisionAffectedRecords } from "./PendingDecisionAffectedRecords";
import type { PendingDecisionValidity } from "./PendingDecisionValidity";
import type { PrincipalKind } from "./PrincipalKind";
import type { PrincipalRef } from "./PrincipalRef";

/**
 * A bounded, typed summary of one pending Decision candidate (design D19,
 * finding F15). `ProjectOverview` exposes these in place of the bare
 * `unresolved_decision_ids` identifier list so every surface can render the
 * question, its alternatives, the Project Agent's recommendation, its
 * rationale, and an approve/reject action without opaque UUIDs or a second
 * fetch. `approve_target`/`reject_target` name the same Decision candidates
 * REST routes the dedicated resource already exposes.
 */
export type PendingDecisionSummary = { id: string, project_id: string, lifecycle: DecisionEditorState, version: bigint, question: string, options: Array<string>, recommendation: string | null, rationale: string | null, decision_class: DecisionClass, affected_records: PendingDecisionAffectedRecords, proposed_by: PrincipalRef,
/**
 * The principal class permitted to approve/reject this candidate.
 * Always `user`: the shared candidate command service rejects any
 * other principal's approval/rejection authorization.
 */
required_principal: PrincipalKind, validity: PendingDecisionValidity,
/**
 * Present only when `validity` is `malformed`; the exact reason no
 * approval action is offered.
 */
invalid_reason: string | null,
/**
 * Absent when `validity` is `malformed`: approving a candidate whose
 * shape violates the D19 invariant would promote that malformed shape
 * into a permanent effective Decision, so no surface may offer it.
 */
approve_target: PendingDecisionActionTarget | null,
/**
 * Always present: rejecting a candidate never propagates its shape
 * into anything consequential, so it remains how a malformed row is
 * cleared.
 */
reject_target: PendingDecisionActionTarget, created_at: string, updated_at: string, };
