// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogModelRate } from "./CatalogModelRate";

/**
 * Cursor-paginated catalog model rates.
 */
export type PricingCatalogModelsResponse = { items: Array<CatalogModelRate>, has_more: boolean, next_cursor: string | null, };
