// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which exact rate source a provider/runtime binding uses.
 */
export type PricingBindingSourceKind = "models_dev_catalog" | "manual_override";
