// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for the opaque-cursor catalog-model listing.
 */
export type PricingCatalogModelsQuery = { limit: number | null, cursor: string | null, provider_id: string | null, query: string | null, };
