// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether Forge can price an agent's next run.
 */
export type PricingResolutionStatus = "priced" | "no_model" | "catalog_absent" | "not_in_catalog" | "ambiguous";
