// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectionAvailability } from "./ProjectionAvailability";
import type { RetryAction } from "./RetryAction";

export type ProjectionStatus = { availability: ProjectionAvailability, retry: RetryAction | null, error_code: string | null, };
