// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityCounts } from "./ActivityCounts";
import type { CostSummary } from "./CostSummary";
import type { TokenCounters } from "./TokenCounters";

/**
 * Aggregate usage for a Project grouping in account analytics.
 */
export type ProjectUsageBreakdown = { project_id: string | null, project_name_snapshot: string | null, counts: ActivityCounts, tokens: TokenCounters, cost: CostSummary, };
