// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CiStepAnalytics } from "./CiStepAnalytics";
import type { ReviewSummaryAnalytics } from "./ReviewSummaryAnalytics";
import type { TokenUsageAnalytics } from "./TokenUsageAnalytics";

export type ProjectAnalyticsResponse = { ci_steps: Array<CiStepAnalytics>, token_usage: TokenUsageAnalytics, review_summary: ReviewSummaryAnalytics, };
