// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyticsWindow } from "./AnalyticsWindow";
import type { CiStepAnalytics } from "./CiStepAnalytics";
import type { OutcomeCostMetric } from "./OutcomeCostMetric";
import type { ReviewSummaryAnalytics } from "./ReviewSummaryAnalytics";
import type { UsageAnalytics } from "./UsageAnalytics";

/**
 * Project analytics for one immutable half-open accounting window.
 */
export type ProjectAnalyticsResponse = { window: AnalyticsWindow, ci_steps: Array<CiStepAnalytics>, token_usage: UsageAnalytics, review_summary: ReviewSummaryAnalytics, outcome_economics: OutcomeCostMetric, };
