// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness of one readiness dimension. `stale` and `unavailable` are
 * explicit because a normal state enum alone cannot distinguish a verified
 * `setup_required` result from a failed projection read.
 */
export type ProjectionAvailability = "current" | "stale" | "unavailable";
