// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectionStatus } from "./ProjectionStatus";

export type ProjectExecutionSetupAvailability = { coordination: ProjectionStatus, execution_setup: ProjectionStatus, execution_gate: ProjectionStatus, };
