// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinationState } from "./CoordinationState";
import type { ExecutionGate } from "./ExecutionGate";
import type { ExecutionPrincipalResponse } from "./ExecutionPrincipalResponse";
import type { ExecutionSetupState } from "./ExecutionSetupState";
import type { ProjectExecutionSetupAvailability } from "./ProjectExecutionSetupAvailability";
import type { ProvisioningOperationResponse } from "./ProvisioningOperationResponse";
import type { RepoResponse } from "./RepoResponse";
import type { RetryAction } from "./RetryAction";
import type { SetupRequirement } from "./SetupRequirement";

export type ProjectExecutionSetupResponse = { project_id: string, project_version: bigint, coordination_state: CoordinationState, execution_setup_state: ExecutionSetupState, execution_gate: ExecutionGate, availability: ProjectExecutionSetupAvailability, primary_repo: RepoResponse | null, worker: ExecutionPrincipalResponse | null, independent_reviewer: ExecutionPrincipalResponse | null, eligible_workers: Array<ExecutionPrincipalResponse>, eligible_reviewers: Array<ExecutionPrincipalResponse>, setup_requirements: Array<SetupRequirement>, next_action: RetryAction | null, provisioning: ProvisioningOperationResponse | null, };
