// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentAsset } from "./EnvironmentAsset";
import type { EnvironmentCheck } from "./EnvironmentCheck";

/**
 * What every Task execution in a Project needs from its host, declared once
 * instead of being rediscovered by each agent run.
 *
 * Forge applies it immediately before an execution launches: `env` is set on
 * the executor process (and on review steps and lifecycle hooks), `assets`
 * are copied into the worktree, and the `checks` for the execution's role
 * must pass or the Task is parked as `environment_not_ready` without
 * spending an agent run.
 */
export type ProjectEnvironment = { env: { [key in string]?: string }, assets: Array<EnvironmentAsset>, checks: Array<EnvironmentCheck>, };
