// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Last observed provider-call health. Error text is a bounded redacted reason;
 * no response bodies or credentials are exposed.
 */
export type ProviderEntryHealthResponse = { status: string, consecutive_failures: number, last_error_kind: string | null, last_error_message: string | null, last_failure_at: string | null, backoff_until: string | null, };
