// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A USD rate per one million tokens.
 */
export type RateAmount = {
/**
 * Always `USD` in this API revision.
 */
currency: "USD",
/**
 * Canonical non-negative decimal text; never an exponent.
 */
decimal_per_million: string, };
