// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness overlay for the immutable readiness snapshot shown in a live
 * Overview. The snapshot remains inspectable when stale; this overlay is the
 * only field that tells callers whether it may be used for a release.
 */
export type ReadinessFreshnessStatus = "current" | "stale" | "unavailable";
