// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReconciliationRecordRef } from "./ReconciliationRecordRef";

/**
 * The immutable canonical conflict a reconciliation was opened against.
 */
export type ReconciliationConflictSummary = { id: string, domain: string, governing: ReconciliationRecordRef, conflicting: ReconciliationRecordRef, affected_paths: Array<string>, conflict_code: string, description: string, detected_by_type: string, detected_by_id: string | null, created_at: string, };
