// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reconciliation's lifecycle state: `Required` until an explicit
 * resolution advances it to one of the four other terminal values.
 */
export type ReconciliationState = "required" | "retained" | "revised" | "cancelled" | "superseded" | "invalidated";
