// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The five terminal outcomes a reconciliation resolution may record. This
 * mirrors the closed `CHECK` on `project_reconciliation_record.state` and
 * `project_reconciliation_resolution.action` exactly; there is no sixth
 * value and no free-form escape hatch.
 */
export type ReconciliationResolutionAction = "retained" | "revised" | "cancelled" | "superseded" | "invalidated";
