// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageTelemetryState } from "./UsageTelemetryState";

/**
 * Per-attempt usage transported over the daemon command stream.
 *
 * Counters are nullable independently: a reported-money-only event, a
 * partially observed stream, and a producer with no telemetry are all
 * materially different from an explicit metered zero. `reported_cost_usd`
 * remains exact decimal text on the wire; clients must not parse it through a
 * binary floating-point number.
 */
export type RemoteUsageReport = { report_id: string, request_id: string | null, report_sequence: number, candidate_key: string | null, attempt_ordinal: number, provider_id: string | null, model_id: string | null, input_tokens: bigint | null, output_tokens: bigint | null, cache_read_tokens: bigint | null, cache_write_tokens: bigint | null, telemetry_state: UsageTelemetryState, context_tokens: bigint | null, selected_tier: string | null, reported_cost_usd: string | null, partial: boolean, };
