// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingBindingSourceKind } from "./PricingBindingSourceKind";
import type { RateBuckets } from "./RateBuckets";

/**
 * Desired exact binding in a replace-all pricing mutation.
 */
export type ReplaceProviderPricingBinding = { runtime_model: string, source_kind: PricingBindingSourceKind, catalog_provider_id: string | null, catalog_model_id: string | null, catalog_rate_revision_id: string | null, manual_rates: RateBuckets | null, };
