// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplaceProviderPricingBinding } from "./ReplaceProviderPricingBinding";

/**
 * Replace the complete exact binding set for a provider/runtime subject.
 */
export type ReplaceProviderPricingRequest = { expected_version: number, idempotency_key: string, subject_revision_digest: string, bindings: Array<ReplaceProviderPricingBinding>, };
