// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonRepoLocationKind } from "./DaemonRepoLocationKind";
import type { RepoLocationProbe } from "./RepoLocationProbe";

export type RepoLocationVerifyParams = { repo_location_id: string, daemon_id: string, runtime_id: string, path: string, kind: DaemonRepoLocationKind, default_branch: string, remote_url: string | null, expected_version: bigint, probe: RepoLocationProbe | null, };
