// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed next action.  Arbitrary command-specific parameters belong in the
 * separately named `arguments` map and are only populated by a command that
 * has validated those parameters for the caller's scope.
 */
export type RetryAction = "refresh_and_retry" | "use_new_idempotency_key" | "repropose" | "reauthorize" | "complete_setup" | "retry_after" | "correct_input" | "select_worker" | "select_independent_reviewer" | "attach_repository" | "retry_provisioning";
