// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetryAction } from "./RetryAction";

/**
 * Bounded corrective information for an outcome.
 */
export type RetryInstruction = { action: RetryAction, retryable: boolean, after_seconds: bigint | null, arguments: Record<string, unknown>, };
