// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewEvidenceRef = { "kind": "file", path: string, commit_sha: string, start_line: number, end_line: number, } | { "kind": "check", check_id: string, };
