// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewSummaryAnalytics = { total_reviews: bigint, passed: bigint, failed: bigint, cancelled: bigint, avg_duration_ms: bigint | null, pass_rate: number, };
