// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Review counts remain separate from token/cost analytics.
 */
export type ReviewSummaryAnalytics = { total_reviews: number, passed: number, failed: number, cancelled: number, avg_duration_ms: number | null, pass_rate: number, };
