// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binds one agent to the account's Main scope. The binding follows the
 * agent's current settings; the stored profile snapshot is server-resolved.
 */
export type SetMainAgentBindingRequest = { identity_id: string, expected_version: bigint, autonomy_policy: Record<string, unknown>, };
