// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductMaturity } from "./ProductMaturity";

export type StartProductGenesisRequest = { idempotency_key: string, maturity: ProductMaturity | null, initial_idea: string | null, preferred_project_agent_identity_id: string | null, };
