// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `label`/`summary` are optional -- an empty request still starts a topic
 * with a server-assigned default label.
 */
export type StartAgentChatTopicRequest = { label: string | null, summary: string | null, };
