// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingSettings } from "./PricingSettings";

/**
 * A provider entry's or CLI runtime's pricing adjustment. `settings` is
 * `null` when it uses list price with inferred models.dev rows.
 */
export type SubjectPricingResponse = { settings: PricingSettings | null, };
