// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a Project's tokens were spent. Task executions are only part of the
 * bill: the Genesis discovery that produced the Project and the Project
 * Agent's own orchestration turns are recorded on chat messages, and for a
 * small Project they routinely outweigh the code work.
 */
export type SurfaceTokenBreakdown = { 
/**
 * `task_execution`, `project_chat`, or `genesis_chat`.
 */
surface: string, 
/**
 * Task executions for `task_execution`, Agent Chat turns otherwise.
 */
run_count: bigint, input_tokens: bigint, output_tokens: bigint, cache_read_tokens: bigint, cache_write_tokens: bigint, cost_usd: number | null, };
