// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskDetailExecutionsPage } from "./TaskDetailExecutionsPage";
import type { TaskResponse } from "./TaskResponse";
import type { WorkflowDefinition } from "./WorkflowDefinition";

export type TaskDetailResponse = { task: TaskResponse, workflow: WorkflowDefinition, executions: TaskDetailExecutionsPage, };
