// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskRelationSummary } from "./TaskRelationSummary";

/**
 * Direct relations for a task, loaded without scanning its whole project.
 */
export type TaskRelationsResponse = { parent: TaskRelationSummary | null, subtasks: Array<TaskRelationSummary>, dependencies: Array<TaskRelationSummary>, missing_dependency_ids: Array<string>, dependents: Array<TaskRelationSummary>, };
