// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalPhase } from "./CanonicalPhase";
import type { StateKind } from "./StateKind";

export type TaskWorkflowStateSnapshot = { name: string, kind: StateKind, canonical_phase: CanonicalPhase, requires_user_approval: boolean, is_cancellation: boolean, };
