// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskResponse } from "./TaskResponse";

export type TaskProposalCommandResponse = { operation: string, status: string, materialized: boolean, domain_committed: boolean, receipt_id: string, event_id: string, input_digest: string, policy_result: string, correlation_id: string, replayed: boolean, requires_user_authorization: boolean, task: TaskResponse, };
