// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskWorkflowStateSnapshot } from "./TaskWorkflowStateSnapshot";

export type TaskWorkflowTransitionSnapshot = { definition_digest: string, parent_task_id: string | null, source_task_version: bigint, from_state: TaskWorkflowStateSnapshot, to_state: TaskWorkflowStateSnapshot, };
