// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskWorkflowTransitionSnapshot } from "./TaskWorkflowTransitionSnapshot";

export type TaskTransitionEventPayload = { transition_log_id: string, project_id: string, from_state: string, to_state: string, trigger_name: string | null, trigger_reason: string, rejection: boolean, workflow_snapshot?: TaskWorkflowTransitionSnapshot, };
