// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostSummary } from "./CostSummary";
import type { TokenCounters } from "./TokenCounters";

export type TokenTotalsSummary = { tokens: TokenCounters, cost: CostSummary, };
