// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTokenBreakdown } from "./AgentTokenBreakdown";
import type { ModelTokenBreakdown } from "./ModelTokenBreakdown";
import type { SurfaceTokenBreakdown } from "./SurfaceTokenBreakdown";

export type TokenUsageAnalytics = { total_input_tokens: bigint, total_output_tokens: bigint, total_cache_read_tokens: bigint, total_cache_write_tokens: bigint, total_cost_usd: number | null, execution_count: bigint, 
/**
 * Agent Chat turns counted in the totals, across both chat surfaces.
 */
chat_turn_count: bigint, by_model: Array<ModelTokenBreakdown>, by_agent: Array<AgentTokenBreakdown>, by_surface: Array<SurfaceTokenBreakdown>, };
