// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutcomeCode } from "./OutcomeCode";
import type { OutcomeStatus } from "./OutcomeStatus";
import type { RetryAction } from "./RetryAction";

/**
 * A bounded, redaction-safe summary of one tool call's outcome.
 *
 * This is the one shape carried across the runtime-event boundary
 * (`TurnEventSink::tool_call_finished`), the durable execution/chat log, the
 * model-visible tool result, and the UI tool card, so all four surfaces
 * agree on the same code, message, retryability, and correlation id for a
 * completed tool call. Only fields already vetted safe for a caller belong
 * here: raw tool arguments, raw payloads, credentials, protected internal
 * causes, and unredacted internal error text must never be added to this
 * type or assigned into `safe_message`.
 */
export type ToolResultSummary = { status: OutcomeStatus, code: OutcomeCode, safe_message: string, retryable: boolean, recovery_action: RetryAction | null, correlation_id: string, };
