// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Product surface that produced one provider invocation.
 */
export type UsageSurface = "task_execution" | "project_chat" | "main_chat" | "genesis_chat" | "main_inquiry";
