// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityCounts } from "./ActivityCounts";
import type { CostSummary } from "./CostSummary";
import type { TokenCounters } from "./TokenCounters";

export type UsageSummary = { counts: ActivityCounts, tokens: TokenCounters, cost: CostSummary, active_execution_count: number, };
