// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityCounts } from "./ActivityCounts";
import type { CostSummary } from "./CostSummary";
import type { TokenCounters } from "./TokenCounters";

/**
 * Shared aggregate used by every analytics grouping.
 */
export type UsageAggregate = { counts: ActivityCounts, tokens: TokenCounters, cost: CostSummary, };
