// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attribution captured when a usage event is admitted.
 */
export type UsageAttribution = { pricing_subject_revision: string | null, agent_id: string | null, profile_id: string | null, executor_type: string | null, provider_id: string | null, model_id: string | null, candidate_key: string | null, attempt_ordinal: number, };
