// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostCoverageReason } from "./CostCoverageReason";
import type { TokenCounters } from "./TokenCounters";

/**
 * Run/turn and provider-attempt coverage dimensions for one cost summary.
 */
export type UsageCostCoverage = { total_runs_or_turns: number, pending_runs_or_turns: number, no_provider_call_runs_or_turns: number, fully_metered_runs_or_turns: number, fully_costed_runs_or_turns: number, partially_costed_runs_or_turns: number, unavailable_cost_runs_or_turns: number, total_provider_attempts: number, settled_provider_attempts: number, pending_provider_attempts: number, unsettled_provider_attempts: number, metered_provider_attempts: number, unmetered_provider_attempts: number, costed_provider_attempts: number, unpriced_provider_attempts: number, priced_tokens: TokenCounters, unpriced_tokens: TokenCounters, reasons: Array<CostCoverageReason>, };
