// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceOperationExpected } from "./WorkspaceOperationExpected";
import type { WorkspaceOwnerOperation } from "./WorkspaceOwnerOperation";

export type WorkspaceOwnerOperationParams = { workspace_handle: string, operation: WorkspaceOwnerOperation, daemon_id: string, runtime_id: string, placement_id: string, operation_id: string, generation: bigint, expected: WorkspaceOperationExpected, };
