// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceGitQuery } from "./WorkspaceGitQuery";

/**
 * Additional structured workspace.read inputs used by owner-local services.
 */
export type WorkspaceInspectParams = { "operation": "git", query: WorkspaceGitQuery, optional: boolean, limit: bigint, daemon_id: string, runtime_id: string, placement_id: string, workspace_handle: string, generation: bigint, } | { "operation": "paths", daemon_id: string, runtime_id: string, placement_id: string, workspace_handle: string, generation: bigint, } | { "operation": "files", path: string, 
/**
 * Read the verified repository location instead of the worktree.
 */
repository: boolean, max_entries: bigint, max_bytes: bigint, daemon_id: string, runtime_id: string, placement_id: string, workspace_handle: string, generation: bigint, };
