// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceOwnerOperationOutcome = { "kind": "applied" } | { "kind": "review_checkout", workspace_handle: string, } | { "kind": "rebased" } | { "kind": "conflict", details: string, conflict_paths: Array<string>, } | { "kind": "unsupported_conflict", details: string, } | { "kind": "dirty", files: Array<string>, };
