// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fixed Git queries, never an arbitrary Git argv or a shell command.
 */
export type WorkspaceGitQuery = { "kind": "head" } | { "kind": "resolve_ref", reference: string, } | { "kind": "merge_base", base_ref: string, head_ref: string, } | { "kind": "candidate_paths", base_sha: string, commit_sha: string, } | { "kind": "tracked_changes" } | { "kind": "status_porcelain" } | { "kind": "branch_exists", branch: string, } | { "kind": "rebase_in_progress" } | { "kind": "target_head", branch: string, };
