// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceDescribeResult = { workspace_handle: string, generation: bigint, exists: boolean, head_sha: string | null, dirty: boolean, branch: string | null, locked: boolean, active_execution_ids: Array<string>, journaled_execution_ids: Array<string>, };
