// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDiffFileStatus } from "./WorkspaceDiffFileStatus";

export type WorkspaceDiffFile = { path: string, status: WorkspaceDiffFileStatus, additions: bigint, deletions: bigint, };
