// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceOwnerOperationOutcome } from "./WorkspaceOwnerOperationOutcome";

export type WorkspaceOwnerOperationResult = { entry_id: string, operation_id: string, outcome: WorkspaceOwnerOperationOutcome, };
