// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceCleanupResult = { entry_id: string, operation_id: string, workspace_handle: string, generation: bigint, cleaned: boolean, };
