// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceOperationExpected } from "./WorkspaceOperationExpected";

export type WorkspaceResetParams = { workspace_handle: string, base_ref: string, branch: string, daemon_id: string, runtime_id: string, placement_id: string, operation_id: string, generation: bigint, expected: WorkspaceOperationExpected, };
