// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceOperationExpected } from "./WorkspaceOperationExpected";

export type WorkspaceMergeParams = { workspace_handle: string, repo_location_id: string, target_branch: string, expected_target_sha: string, handed_off_paths: Array<string>, daemon_id: string, runtime_id: string, placement_id: string, operation_id: string, generation: bigint, expected: WorkspaceOperationExpected, };
