// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceOperationExpected } from "./WorkspaceOperationExpected";
import type { WorkspaceRunPurpose } from "./WorkspaceRunPurpose";

export type WorkspaceRunParams = { workspace_handle: string, purpose: WorkspaceRunPurpose, command: string, env: Array<[string, string]>, 
/**
 * Zero preserves the CI runner's unbounded duration (ci_step only).
 */
timeout_secs: bigint, 
/**
 * u64::MAX preserves full CI output; other values are strict per-stream budgets.
 */
max_output_bytes: bigint, daemon_id: string, runtime_id: string, placement_id: string, operation_id: string, generation: bigint, expected: WorkspaceOperationExpected, };
