// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDiffStats } from "./WorkspaceDiffStats";
import type { WorkspaceMergeOutcome } from "./WorkspaceMergeOutcome";

export type WorkspaceMergeResult = { entry_id: string, operation_id: string, outcome: WorkspaceMergeOutcome, diffstat: WorkspaceDiffStats | null, };
