#![forbid(unsafe_code)]

pub mod assignee;
mod auth;

mod actor;
mod agent_chats;
mod agent_inquiries;
mod analytics;
mod coordination;
mod core;
mod daemon_transport;
mod execution;
mod execution_blocker;
mod execution_setup;
mod git;
mod integration;
mod lists;
mod mcp;
mod memory;
mod mission_control;
mod oauth;
mod operations;
mod orchestration_outcome;
mod pricing;
mod product_genesis;
mod project_hooks;
mod project_orchestration;
mod provider_auth;
mod repo_review;
mod requests;
mod review_conformance;
mod runtime;
mod settings;
mod terminal;
mod workflow;

pub use actor::*;
pub use agent_chats::*;
pub use agent_inquiries::*;
pub use analytics::*;
pub use auth::*;
pub use coordination::*;
pub use core::*;
pub use daemon_transport::*;
pub use execution::*;
pub use execution_blocker::*;
pub use execution_setup::*;
pub use git::*;
pub use integration::*;
pub use lists::*;
pub use mcp::*;
pub use memory::*;
pub use mission_control::*;
pub use oauth::*;
pub use operations::*;
pub use orchestration_outcome::*;
pub use pricing::*;
pub use product_genesis::*;
pub use project_hooks::*;
pub use project_orchestration::*;
pub use provider_auth::*;
pub use repo_review::*;
pub use requests::*;
pub use review_conformance::*;
pub use runtime::*;
pub use settings::*;
pub use terminal::*;
pub use workflow::*;

#[test]
#[ignore = "manual type export for the web client"]
fn export_typescript() {
    use ts_rs::TS;

    let out_dir =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/types/generated");
    std::fs::create_dir_all(&out_dir).expect("create types output directory");
    std::env::set_current_dir(&out_dir).expect("switch to types output directory");
    let cfg = ts_rs::Config::new();

    TaskType::export(&cfg).expect("export TaskType");
    ProductMaturity::export(&cfg).expect("export ProductMaturity");
    ProductGenesisLifecycle::export(&cfg).expect("export ProductGenesisLifecycle");
    ProductGenesisSession::export(&cfg).expect("export ProductGenesisSession");
    StartProductGenesisRequest::export(&cfg).expect("export StartProductGenesisRequest");
    ProductGenesisStartResponse::export(&cfg).expect("export ProductGenesisStartResponse");
    ProductGenesisActiveResponse::export(&cfg).expect("export ProductGenesisActiveResponse");
    CancelProductGenesisRequest::export(&cfg).expect("export CancelProductGenesisRequest");
    ApplyProductGenesisGuidedSetupRequest::export(&cfg)
        .expect("export ApplyProductGenesisGuidedSetupRequest");
    WorkMode::export(&cfg).expect("export WorkMode");
    CreateRepoRequest::export(&cfg).expect("export CreateRepoRequest");
    UpdateRepoRequest::export(&cfg).expect("export UpdateRepoRequest");
    RepoResponse::export(&cfg).expect("export RepoResponse");
    RepoSyncResponse::export(&cfg).expect("export RepoSyncResponse");
    FsEntry::export(&cfg).expect("export FsEntry");
    FsListResponse::export(&cfg).expect("export FsListResponse");
    BranchListResponse::export(&cfg).expect("export BranchListResponse");
    ReviewRequirement::export(&cfg).expect("export ReviewRequirement");
    ConformanceCheck::export(&cfg).expect("export ConformanceCheck");
    ReviewGoverningContext::export(&cfg).expect("export ReviewGoverningContext");
    ReviewContract::export(&cfg).expect("export ReviewContract");
    ConformanceVerdict::export(&cfg).expect("export ConformanceVerdict");
    RequirementDisposition::export(&cfg).expect("export RequirementDisposition");
    ReviewEvidenceRef::export(&cfg).expect("export ReviewEvidenceRef");
    RequirementAssessment::export(&cfg).expect("export RequirementAssessment");
    ConformanceFinding::export(&cfg).expect("export ConformanceFinding");
    ReviewAssessment::export(&cfg).expect("export ReviewAssessment");
    ConformanceStatus::export(&cfg).expect("export ConformanceStatus");
    ConformanceCheckResult::export(&cfg).expect("export ConformanceCheckResult");
    ReviewConformance::export(&cfg).expect("export ReviewConformance");
    ReviewConfig::export(&cfg).expect("export ReviewConfig");
    RetryBudgets::export(&cfg).expect("export RetryBudgets");
    AutomaticRecoverySettings::export(&cfg).expect("export AutomaticRecoverySettings");
    LifecycleEvent::export(&cfg).expect("export LifecycleEvent");
    LifecycleHookDef::export(&cfg).expect("export LifecycleHookDef");
    ProjectSettings::export(&cfg).expect("export ProjectSettings");
    LifecycleHookTestResponse::export(&cfg).expect("export LifecycleHookTestResponse");
    TaskMetadata::export(&cfg).expect("export TaskMetadata");
    Task::export(&cfg).expect("export Task");
    TaskAction::export(&cfg).expect("export TaskAction");
    TaskActionsResponse::export(&cfg).expect("export TaskActionsResponse");
    StopReason::export(&cfg).expect("export StopReason");
    ResumePolicy::export(&cfg).expect("export ResumePolicy");
    RecoveryAction::export(&cfg).expect("export RecoveryAction");
    ExecutionBehaviorKind::export(&cfg).expect("export ExecutionBehaviorKind");
    ExecutionBehavior::export(&cfg).expect("export ExecutionBehavior");
    ExecutionActionKind::export(&cfg).expect("export ExecutionActionKind");
    ExecutionAction::export(&cfg).expect("export ExecutionAction");
    BlockingArtifact::export(&cfg).expect("export BlockingArtifact");
    TaskBlockingAnnotation::export(&cfg).expect("export TaskBlockingAnnotation");
    InterruptionMetadata::export(&cfg).expect("export InterruptionMetadata");
    TaskAnnotation::export(&cfg).expect("export TaskAnnotation");
    TaskExecutionObservability::export(&cfg).expect("export TaskExecutionObservability");
    TaskResponse::export(&cfg).expect("export TaskResponse");
    TaskRelationSummary::export(&cfg).expect("export TaskRelationSummary");
    TaskRelationsResponse::export(&cfg).expect("export TaskRelationsResponse");
    ExecutionStatus::export(&cfg).expect("export ExecutionStatus");
    ExecutionOwnerHealth::export(&cfg).expect("export ExecutionOwnerHealth");
    ExecutionInterruptionResponse::export(&cfg).expect("export ExecutionInterruptionResponse");
    ExecutionResponse::export(&cfg).expect("export ExecutionResponse");
    TaskDetailExecutionsPage::export(&cfg).expect("export TaskDetailExecutionsPage");
    TaskDetailResponse::export(&cfg).expect("export TaskDetailResponse");
    CoordinationState::export(&cfg).expect("export CoordinationState");
    ExecutionSetupState::export(&cfg).expect("export ExecutionSetupState");
    ExecutionGate::export(&cfg).expect("export ExecutionGate");
    ProjectionAvailability::export(&cfg).expect("export ProjectionAvailability");
    ProjectionStatus::export(&cfg).expect("export ProjectionStatus");
    ProjectExecutionSetupAvailability::export(&cfg)
        .expect("export ProjectExecutionSetupAvailability");
    ExecutionPrincipalResponse::export(&cfg).expect("export ExecutionPrincipalResponse");
    ProvisioningOperationResponse::export(&cfg).expect("export ProvisioningOperationResponse");
    ProjectExecutionSetupResponse::export(&cfg).expect("export ProjectExecutionSetupResponse");
    ExecutionBlockerStage::export(&cfg).expect("export ExecutionBlockerStage");
    ExecutionBlockerScope::export(&cfg).expect("export ExecutionBlockerScope");
    ExecutionBlockerPrincipal::export(&cfg).expect("export ExecutionBlockerPrincipal");
    ExecutionBlockerCode::export(&cfg).expect("export ExecutionBlockerCode");
    ExecutionBlockerRecordRef::export(&cfg).expect("export ExecutionBlockerRecordRef");
    ExecutionProgress::export(&cfg).expect("export ExecutionProgress");
    ExecutionEvidenceSummary::export(&cfg).expect("export ExecutionEvidenceSummary");
    ExecutionBlockerProjection::export(&cfg).expect("export ExecutionBlockerProjection");
    SelectExecutionPrincipalRequest::export(&cfg).expect("export SelectExecutionPrincipalRequest");
    AttachPrimaryRepositoryRequest::export(&cfg).expect("export AttachPrimaryRepositoryRequest");
    RetryProvisioningRequest::export(&cfg).expect("export RetryProvisioningRequest");
    PromptPreviewResponse::export(&cfg).expect("export PromptPreviewResponse");
    MemorySearchQuery::export(&cfg).expect("export MemorySearchQuery");
    MemoryGetQuery::export(&cfg).expect("export MemoryGetQuery");
    MemorySearchResultDto::export(&cfg).expect("export MemorySearchResultDto");
    MemorySearchResponse::export(&cfg).expect("export MemorySearchResponse");
    MemoryPublicationRequest::export(&cfg).expect("export MemoryPublicationRequest");
    MemoryLifecycleRequest::export(&cfg).expect("export MemoryLifecycleRequest");
    MemoryLifecycleResponse::export(&cfg).expect("export MemoryLifecycleResponse");
    MemoryProvenanceResponse::export(&cfg).expect("export MemoryProvenanceResponse");
    ContextManifestQuery::export(&cfg).expect("export ContextManifestQuery");
    ContextManifestListQuery::export(&cfg).expect("export ContextManifestListQuery");
    ContextManifestSourceResponse::export(&cfg).expect("export ContextManifestSourceResponse");
    ContextManifestResponse::export(&cfg).expect("export ContextManifestResponse");
    ContextManifestListResponse::export(&cfg).expect("export ContextManifestListResponse");
    MemoryProvenanceQuery::export(&cfg).expect("export MemoryProvenanceQuery");
    AttentionLifecycle::export(&cfg).expect("export AttentionLifecycle");
    AttentionCategory::export(&cfg).expect("export AttentionCategory");
    AttentionItem::export(&cfg).expect("export AttentionItem");
    AttentionListResponse::export(&cfg).expect("export AttentionListResponse");
    AttentionConsumerHealthResponse::export(&cfg).expect("export AttentionConsumerHealthResponse");
    AttentionMutationRequest::export(&cfg).expect("export AttentionMutationRequest");
    AttentionSnoozeRequest::export(&cfg).expect("export AttentionSnoozeRequest");
    MissionControlWorkItem::export(&cfg).expect("export MissionControlWorkItem");
    MissionControlAgentHealth::export(&cfg).expect("export MissionControlAgentHealth");
    MissionControlRecentOutcome::export(&cfg).expect("export MissionControlRecentOutcome");
    MissionControlCoordinationActivity::export(&cfg)
        .expect("export MissionControlCoordinationActivity");
    MissionControlCapacity::export(&cfg).expect("export MissionControlCapacity");
    MissionControlHomeResponse::export(&cfg).expect("export MissionControlHomeResponse");
    MissionControlQuery::export(&cfg).expect("export MissionControlQuery");
    AgentDetailResponse::export(&cfg).expect("export AgentDetailResponse");
    AgentBindingSummary::export(&cfg).expect("export AgentBindingSummary");
    AgentScopeSummary::export(&cfg).expect("export AgentScopeSummary");
    AgentSessionSummary::export(&cfg).expect("export AgentSessionSummary");
    AgentContinuityHealth::export(&cfg).expect("export AgentContinuityHealth");
    TerminalSessionStatus::export(&cfg).expect("export TerminalSessionStatus");
    TerminalSessionResponse::export(&cfg).expect("export TerminalSessionResponse");
    CreateTerminalSessionRequest::export(&cfg).expect("export CreateTerminalSessionRequest");
    ResizeTerminalSessionRequest::export(&cfg).expect("export ResizeTerminalSessionRequest");
    TerminalAttachTokenResponse::export(&cfg).expect("export TerminalAttachTokenResponse");
    TerminalAvailability::export(&cfg).expect("export TerminalAvailability");
    TerminalClientFrame::export(&cfg).expect("export TerminalClientFrame");
    TerminalServerFrame::export(&cfg).expect("export TerminalServerFrame");
    TasksResponse::export(&cfg).expect("export TasksResponse");
    MoveTaskRequest::export(&cfg).expect("export MoveTaskRequest");
    MoveTaskResponse::export(&cfg).expect("export MoveTaskResponse");
    OperationConflictDetails::export(&cfg).expect("export OperationConflictDetails");
    TaskVersionConflictDetails::export(&cfg).expect("export TaskVersionConflictDetails");
    BoardRevisionConflictDetails::export(&cfg).expect("export BoardRevisionConflictDetails");
    TaskMovedEventPayload::export(&cfg).expect("export TaskMovedEventPayload");
    Agent::export(&cfg).expect("export Agent");
    AgentStatus::export(&cfg).expect("export AgentStatus");
    AgentResponse::export(&cfg).expect("export AgentResponse");
    AgentsResponse::export(&cfg).expect("export AgentsResponse");
    Project::export(&cfg).expect("export Project");
    ProjectResponse::export(&cfg).expect("export ProjectResponse");
    ProjectHookRule::export(&cfg).expect("export ProjectHookRule");
    ProjectHookTrigger::export(&cfg).expect("export ProjectHookTrigger");
    ProjectHookAction::export(&cfg).expect("export ProjectHookAction");
    ProjectHookRunStatus::export(&cfg).expect("export ProjectHookRunStatus");
    ProjectHookRunResponse::export(&cfg).expect("export ProjectHookRunResponse");
    ProjectHookRunsResponse::export(&cfg).expect("export ProjectHookRunsResponse");
    ProjectsResponse::export(&cfg).expect("export ProjectsResponse");
    AgentBindingState::export(&cfg).expect("export AgentBindingState");
    AgentChatKind::export(&cfg).expect("export AgentChatKind");
    AgentChatStatus::export(&cfg).expect("export AgentChatStatus");
    AgentChatMessageAuthorType::export(&cfg).expect("export AgentChatMessageAuthorType");
    AgentChatMessageStatus::export(&cfg).expect("export AgentChatMessageStatus");
    AgentChatTurnStatus::export(&cfg).expect("export AgentChatTurnStatus");
    AgentHandoffStatus::export(&cfg).expect("export AgentHandoffStatus");
    MainAgentBindingResponse::export(&cfg).expect("export MainAgentBindingResponse");
    ProjectAgentBindingResponse::export(&cfg).expect("export ProjectAgentBindingResponse");
    SetMainAgentBindingRequest::export(&cfg).expect("export SetMainAgentBindingRequest");
    SetProjectAgentBindingRequest::export(&cfg).expect("export SetProjectAgentBindingRequest");
    AgentChatResponse::export(&cfg).expect("export AgentChatResponse");
    AgentChatDetailResponse::export(&cfg).expect("export AgentChatDetailResponse");
    AgentChatSwitcherItem::export(&cfg).expect("export AgentChatSwitcherItem");
    AgentChatSwitcherResponse::export(&cfg).expect("export AgentChatSwitcherResponse");
    AgentChatMessageResponse::export(&cfg).expect("export AgentChatMessageResponse");
    AgentChatTurnJobResponse::export(&cfg).expect("export AgentChatTurnJobResponse");
    SendAgentChatMessageRequest::export(&cfg).expect("export SendAgentChatMessageRequest");
    SendAgentChatMessageResponse::export(&cfg).expect("export SendAgentChatMessageResponse");
    CancelAgentChatTurnRequest::export(&cfg).expect("export CancelAgentChatTurnRequest");
    CreateAgentHandoffRequest::export(&cfg).expect("export CreateAgentHandoffRequest");
    AgentHandoffResponse::export(&cfg).expect("export AgentHandoffResponse");
    AgentChatListQuery::export(&cfg).expect("export AgentChatListQuery");
    AgentChatListResponse::export(&cfg).expect("export AgentChatListResponse");
    AgentChatMessagesQuery::export(&cfg).expect("export AgentChatMessagesQuery");
    AgentChatMessageListResponse::export(&cfg).expect("export AgentChatMessageListResponse");
    AgentInquiryStatus::export(&cfg).expect("export AgentInquiryStatus");
    AgentInquiryTokenUsage::export(&cfg).expect("export AgentInquiryTokenUsage");
    AgentInquiryResponse::export(&cfg).expect("export AgentInquiryResponse");
    AgentInquiryListResponse::export(&cfg).expect("export AgentInquiryListResponse");
    CancelAgentInquiryRequest::export(&cfg).expect("export CancelAgentInquiryRequest");
    CreateEmbeddedAgentRequest::export(&cfg).expect("export CreateEmbeddedAgentRequest");
    ConnectEmbeddedProfileRequest::export(&cfg).expect("export ConnectEmbeddedProfileRequest");
    CanonicalScopeRequest::export(&cfg).expect("export CanonicalScopeRequest");
    CreateAgentSessionRequest::export(&cfg).expect("export CreateAgentSessionRequest");
    SessionVersionRequest::export(&cfg).expect("export SessionVersionRequest");
    SteerAgentSessionRequest::export(&cfg).expect("export SteerAgentSessionRequest");
    CredentialHandleResponse::export(&cfg).expect("export CredentialHandleResponse");
    ProviderRevocationStatus::export(&cfg).expect("export ProviderRevocationStatus");
    DisconnectCredentialResponse::export(&cfg).expect("export DisconnectCredentialResponse");
    AgentProfileResponse::export(&cfg).expect("export AgentProfileResponse");
    AgentConnectionHealthResponse::export(&cfg).expect("export AgentConnectionHealthResponse");
    AgentSessionResponse::export(&cfg).expect("export AgentSessionResponse");
    ProtectedInteractionSummaryResponse::export(&cfg)
        .expect("export ProtectedInteractionSummaryResponse");
    ProtectedInteractionAnswerRequest::export(&cfg)
        .expect("export ProtectedInteractionAnswerRequest");
    ProtectedInteractionAnswerValue::export(&cfg).expect("export ProtectedInteractionAnswerValue");
    ProtectedInteractionCancelRequest::export(&cfg)
        .expect("export ProtectedInteractionCancelRequest");
    ConnectedEmbeddedAgentResponse::export(&cfg).expect("export ConnectedEmbeddedAgentResponse");
    ConnectedEmbeddedProfileResponse::export(&cfg)
        .expect("export ConnectedEmbeddedProfileResponse");
    EffectivePermissionsResponse::export(&cfg).expect("export EffectivePermissionsResponse");
    AgentProviderId::export(&cfg).expect("export AgentProviderId");
    ProviderCredentialMethod::export(&cfg).expect("export ProviderCredentialMethod");
    ProviderSupportLevel::export(&cfg).expect("export ProviderSupportLevel");
    ProviderRuntimeCapability::export(&cfg).expect("export ProviderRuntimeCapability");
    ProviderCredentialCapability::export(&cfg).expect("export ProviderCredentialCapability");
    AgentProviderCapability::export(&cfg).expect("export AgentProviderCapability");
    AgentProviderCapabilitiesResponse::export(&cfg)
        .expect("export AgentProviderCapabilitiesResponse");
    ProviderEntryAgentRef::export(&cfg).expect("export ProviderEntryAgentRef");
    ProviderEntryHealthResponse::export(&cfg).expect("export ProviderEntryHealthResponse");
    ProviderEntryResponse::export(&cfg).expect("export ProviderEntryResponse");
    CliRuntimeEntryResponse::export(&cfg).expect("export CliRuntimeEntryResponse");
    ProviderEntriesResponse::export(&cfg).expect("export ProviderEntriesResponse");
    ProviderEntryTestResponse::export(&cfg).expect("export ProviderEntryTestResponse");
    CreateProviderEntryRequest::export(&cfg).expect("export CreateProviderEntryRequest");
    RenameProviderEntryRequest::export(&cfg).expect("export RenameProviderEntryRequest");
    SetProviderEntryAvailabilityRequest::export(&cfg)
        .expect("export SetProviderEntryAvailabilityRequest");
    SetCliRuntimeAvailabilityRequest::export(&cfg)
        .expect("export SetCliRuntimeAvailabilityRequest");
    ProviderAuthorizationState::export(&cfg).expect("export ProviderAuthorizationState");
    StartProviderAuthorizationRequest::export(&cfg)
        .expect("export StartProviderAuthorizationRequest");
    CancelProviderAuthorizationRequest::export(&cfg)
        .expect("export CancelProviderAuthorizationRequest");
    ProviderAuthorizationOperationResponse::export(&cfg)
        .expect("export ProviderAuthorizationOperationResponse");
    CommitmentResponse::export(&cfg).expect("export CommitmentResponse");
    CreateCommitmentRequest::export(&cfg).expect("export CreateCommitmentRequest");
    UpdateCommitmentRequest::export(&cfg).expect("export UpdateCommitmentRequest");
    CompleteCommitmentRequest::export(&cfg).expect("export CompleteCommitmentRequest");
    TransferCommitmentRequest::export(&cfg).expect("export TransferCommitmentRequest");
    CommitmentEvidenceResponse::export(&cfg).expect("export CommitmentEvidenceResponse");
    CoordinationListQuery::export(&cfg).expect("export CoordinationListQuery");
    InboxItemResponse::export(&cfg).expect("export InboxItemResponse");
    UpdateInboxItemRequest::export(&cfg).expect("export UpdateInboxItemRequest");
    AskQuestionRequest::export(&cfg).expect("export AskQuestionRequest");
    QuestionResponse::export(&cfg).expect("export QuestionResponse");
    AnswerQuestionRequest::export(&cfg).expect("export AnswerQuestionRequest");
    AgentActionResponse::export(&cfg).expect("export AgentActionResponse");
    ProposeActionRequest::export(&cfg).expect("export ProposeActionRequest");
    TaskProposalRequest::export(&cfg).expect("export TaskProposalRequest");
    ApproveActionRequest::export(&cfg).expect("export ApproveActionRequest");
    ExecuteActionRequest::export(&cfg).expect("export ExecuteActionRequest");
    ExecuteOrchestrationActionRequest::export(&cfg)
        .expect("export ExecuteOrchestrationActionRequest");
    TaskProposalCommandResponse::export(&cfg).expect("export TaskProposalCommandResponse");
    OutcomeCode::export(&cfg).expect("export OutcomeCode");
    OutcomeStatus::export(&cfg).expect("export OutcomeStatus");
    OutcomeScopeType::export(&cfg).expect("export OutcomeScopeType");
    CanonicalScopeRef::export(&cfg).expect("export CanonicalScopeRef");
    ApprovalTarget::export(&cfg).expect("export ApprovalTarget");
    SetupRequirement::export(&cfg).expect("export SetupRequirement");
    CurrentVersionOrRevision::export(&cfg).expect("export CurrentVersionOrRevision");
    RetryAction::export(&cfg).expect("export RetryAction");
    RetryInstruction::export(&cfg).expect("export RetryInstruction");
    OrchestrationOutcome::export(&cfg).expect("export OrchestrationOutcome");
    ToolResultSummary::export(&cfg).expect("export ToolResultSummary");
    ActionExecutionResponse::export(&cfg).expect("export ActionExecutionResponse");
    TaskGovernanceRequest::export(&cfg).expect("export TaskGovernanceRequest");
    TransitionSource::export(&cfg).expect("export TransitionSource");
    TransitionTaskRequest::export(&cfg).expect("export TransitionTaskRequest");
    AuthorType::export(&cfg).expect("export AuthorType");
    TaskMediaResponse::export(&cfg).expect("export TaskMediaResponse");
    RecoverTaskRequest::export(&cfg).expect("export RecoverTaskRequest");
    TaskActionRequest::export(&cfg).expect("export TaskActionRequest");
    TestLifecycleHookRequest::export(&cfg).expect("export TestLifecycleHookRequest");
    CreateCommentRequest::export(&cfg).expect("export CreateCommentRequest");
    StateKind::export(&cfg).expect("export StateKind");
    CleanupPolicy::export(&cfg).expect("export CleanupPolicy");
    FailurePolicy::export(&cfg).expect("export FailurePolicy");
    HookAudience::export(&cfg).expect("export HookAudience");
    GateConfig::export(&cfg).expect("export GateConfig");
    HookSpec::export(&cfg).expect("export HookSpec");
    StateHooks::export(&cfg).expect("export StateHooks");
    CanonicalPhase::export(&cfg).expect("export CanonicalPhase");
    StateDefinition::export(&cfg).expect("export StateDefinition");
    WorkflowTrigger::export(&cfg).expect("export WorkflowTrigger");
    WorkflowExecutionStrategy::export(&cfg).expect("export WorkflowExecutionStrategy");
    WorkflowPromptConfig::export(&cfg).expect("export WorkflowPromptConfig");
    WorkflowDispatch::export(&cfg).expect("export WorkflowDispatch");
    WorkflowTriggerDefinition::export(&cfg).expect("export WorkflowTriggerDefinition");
    RoleDefinition::export(&cfg).expect("export RoleDefinition");
    WorkflowConfigValueType::export(&cfg).expect("export WorkflowConfigValueType");
    WorkflowConfigBinding::export(&cfg).expect("export WorkflowConfigBinding");
    WorkflowConfigField::export(&cfg).expect("export WorkflowConfigField");
    PromptBuilderRegistryEntry::export(&cfg).expect("export PromptBuilderRegistryEntry");
    WorkflowDefinition::export(&cfg).expect("export WorkflowDefinition");
    TaskWorkflowStateSnapshot::export(&cfg).expect("export TaskWorkflowStateSnapshot");
    TaskWorkflowTransitionSnapshot::export(&cfg).expect("export TaskWorkflowTransitionSnapshot");
    TaskTransitionEventPayload::export(&cfg).expect("export TaskTransitionEventPayload");
    WorkflowTemplateSummary::export(&cfg).expect("export WorkflowTemplateSummary");
    WorkflowTemplateResponse::export(&cfg).expect("export WorkflowTemplateResponse");
    SaveWorkflowTemplateRequest::export(&cfg).expect("export SaveWorkflowTemplateRequest");
    UpdateProjectWorkflowRequest::export(&cfg).expect("export UpdateProjectWorkflowRequest");
    TaskRoleAssignmentResponse::export(&cfg).expect("export TaskRoleAssignmentResponse");
    AssignRoleRequest::export(&cfg).expect("export AssignRoleRequest");
    assignee::AssigneeKind::export(&cfg).expect("export AssigneeKind");
    DefaultRoleAssignment::export(&cfg).expect("export DefaultRoleAssignment");
    InitialRoleAssignment::export(&cfg).expect("export InitialRoleAssignment");
    TransitionLogEntry::export(&cfg).expect("export TransitionLogEntry");
    HookResultEntry::export(&cfg).expect("export HookResultEntry");
    ReorderSubtasksRequest::export(&cfg).expect("export ReorderSubtasksRequest");
    OperatorSeverity::export(&cfg).expect("export OperatorSeverity");
    OperatorStatusResponse::export(&cfg).expect("export OperatorStatusResponse");
    ActiveExecutionSummary::export(&cfg).expect("export ActiveExecutionSummary");
    BlockedTaskSummary::export(&cfg).expect("export BlockedTaskSummary");
    DaemonIssueSummary::export(&cfg).expect("export DaemonIssueSummary");
    DaemonPressureSummary::export(&cfg).expect("export DaemonPressureSummary");
    AgentPressureSummary::export(&cfg).expect("export AgentPressureSummary");
    WorkspaceCleanupSummary::export(&cfg).expect("export WorkspaceCleanupSummary");
    RetryPressureSummary::export(&cfg).expect("export RetryPressureSummary");
    TokenTotalsSummary::export(&cfg).expect("export TokenTotalsSummary");
    OperationsRefreshResponse::export(&cfg).expect("export OperationsRefreshResponse");
    UsageSummary::export(&cfg).expect("export UsageSummary");
    RecentErrorSummary::export(&cfg).expect("export RecentErrorSummary");
    PlanArtifactDetail::export(&cfg).expect("export PlanArtifactDetail");
    PlanChecklistItem::export(&cfg).expect("export PlanChecklistItem");
    EffectiveExecutionPolicy::export(&cfg).expect("export EffectiveExecutionPolicy");
    PlanProgressSummary::export(&cfg).expect("export PlanProgressSummary");
    SettingsResponse::export(&cfg).expect("export SettingsResponse");
    ForgeSettingResponse::export(&cfg).expect("export ForgeSettingResponse");
    UpdateSettingsRequest::export(&cfg).expect("export UpdateSettingsRequest");
    UpdateForgePathsRequest::export(&cfg).expect("export UpdateForgePathsRequest");
    UpdateServerSettingsRequest::export(&cfg).expect("export UpdateServerSettingsRequest");
    UpdateWorkspaceSettingsRequest::export(&cfg).expect("export UpdateWorkspaceSettingsRequest");
    UpdateAgentSettingsRequest::export(&cfg).expect("export UpdateAgentSettingsRequest");
    RegisterRequest::export(&cfg).expect("export RegisterRequest");
    LoginRequest::export(&cfg).expect("export LoginRequest");
    RefreshRequest::export(&cfg).expect("export RefreshRequest");
    LogoutRequest::export(&cfg).expect("export LogoutRequest");
    AuthResponse::export(&cfg).expect("export AuthResponse");
    UserResponse::export(&cfg).expect("export UserResponse");
    UpdateProfileRequest::export(&cfg).expect("export UpdateProfileRequest");
    OAuthRegisterRequest::export(&cfg).expect("export OAuthRegisterRequest");
    OAuthRegisterResponse::export(&cfg).expect("export OAuthRegisterResponse");
    OAuthApproveRequest::export(&cfg).expect("export OAuthApproveRequest");
    OAuthDecision::export(&cfg).expect("export OAuthDecision");
    OAuthApproveResponse::export(&cfg).expect("export OAuthApproveResponse");
    OAuthAuthorizeContext::export(&cfg).expect("export OAuthAuthorizeContext");
    OAuthErrorResponse::export(&cfg).expect("export OAuthErrorResponse");
    AcceptanceCheckResultStatus::export(&cfg).expect("export AcceptanceCheckResultStatus");
    AcceptanceCheckSourceKind::export(&cfg).expect("export AcceptanceCheckSourceKind");
    AcceptanceCheckSummary::export(&cfg).expect("export AcceptanceCheckSummary");
    AcceptanceEvidenceRequirement::export(&cfg).expect("export AcceptanceEvidenceRequirement");
    AdaptiveEnvelope::export(&cfg).expect("export AdaptiveEnvelope");
    AdaptiveTaskOperation::export(&cfg).expect("export AdaptiveTaskOperation");
    ApproveProjectCharterRequest::export(&cfg).expect("export ApproveProjectCharterRequest");
    ApproveProjectDocumentRequest::export(&cfg).expect("export ApproveProjectDocumentRequest");
    ApproveDecisionCandidateRequest::export(&cfg).expect("export ApproveDecisionCandidateRequest");
    ArchitectureDocumentContent::export(&cfg).expect("export ArchitectureDocumentContent");
    ArtifactRef::export(&cfg).expect("export ArtifactRef");
    AttachEvidenceRequest::export(&cfg).expect("export AttachEvidenceRequest");
    EvidenceAttachmentListResponse::export(&cfg).expect("export EvidenceAttachmentListResponse");
    AuthorizationProvenance::export(&cfg).expect("export AuthorizationProvenance");
    CharterAmendment::export(&cfg).expect("export CharterAmendment");
    CharterAmendmentState::export(&cfg).expect("export CharterAmendmentState");
    CharterApprovalState::export(&cfg).expect("export CharterApprovalState");
    CharterApprovalType::export(&cfg).expect("export CharterApprovalType");
    CharterConfidence::export(&cfg).expect("export CharterConfidence");
    CharterConstraintsAndRisks::export(&cfg).expect("export CharterConstraintsAndRisks");
    CharterCoreExperience::export(&cfg).expect("export CharterCoreExperience");
    CharterHandoffNote::export(&cfg).expect("export CharterHandoffNote");
    CharterIdentity::export(&cfg).expect("export CharterIdentity");
    CharterKnowledgeItem::export(&cfg).expect("export CharterKnowledgeItem");
    CharterKnowledgeKind::export(&cfg).expect("export CharterKnowledgeKind");
    CharterKnowledgeLedger::export(&cfg).expect("export CharterKnowledgeLedger");
    CharterProblemAndPeople::export(&cfg).expect("export CharterProblemAndPeople");
    CharterReadinessGap::export(&cfg).expect("export CharterReadinessGap");
    CharterReadinessGapKind::export(&cfg).expect("export CharterReadinessGapKind");
    CharterReadinessStatus::export(&cfg).expect("export CharterReadinessStatus");
    CharterRevisionLifecycle::export(&cfg).expect("export CharterRevisionLifecycle");
    CharterRisk::export(&cfg).expect("export CharterRisk");
    CharterScope::export(&cfg).expect("export CharterScope");
    CharterScaffold::export(&cfg).expect("export CharterScaffold");
    CharterSuccessBoundary::export(&cfg).expect("export CharterSuccessBoundary");
    CharterSupersession::export(&cfg).expect("export CharterSupersession");
    CreateProjectFromCharterApprovalRequest::export(&cfg)
        .expect("export CreateProjectFromCharterApprovalRequest");
    CreateProjectFromCharterApprovalResponse::export(&cfg)
        .expect("export CreateProjectFromCharterApprovalResponse");
    DecisionCandidate::export(&cfg).expect("export DecisionCandidate");
    DecisionCandidateContext::export(&cfg).expect("export DecisionCandidateContext");
    DecisionCandidateListResponse::export(&cfg).expect("export DecisionCandidateListResponse");
    DecisionClass::export(&cfg).expect("export DecisionClass");
    DecisionEditorState::export(&cfg).expect("export DecisionEditorState");
    DecisionRecord::export(&cfg).expect("export DecisionRecord");
    DecisionRecordListResponse::export(&cfg).expect("export DecisionRecordListResponse");
    DecisionRecordState::export(&cfg).expect("export DecisionRecordState");
    DeliveryBriefContent::export(&cfg).expect("export DeliveryBriefContent");
    DesignDocumentContent::export(&cfg).expect("export DesignDocumentContent");
    DocumentAcceptanceItem::export(&cfg).expect("export DocumentAcceptanceItem");
    DocumentFreshness::export(&cfg).expect("export DocumentFreshness");
    DocumentFreshnessStatus::export(&cfg).expect("export DocumentFreshnessStatus");
    DocumentPlanItem::export(&cfg).expect("export DocumentPlanItem");
    DocumentRevisionLifecycle::export(&cfg).expect("export DocumentRevisionLifecycle");
    CreateMilestoneRequest::export(&cfg).expect("export CreateMilestoneRequest");
    EvaluateMilestoneReadinessRequest::export(&cfg)
        .expect("export EvaluateMilestoneReadinessRequest");
    EvidenceAttachment::export(&cfg).expect("export EvidenceAttachment");
    EvidenceAvailability::export(&cfg).expect("export EvidenceAvailability");
    ReleaseEvidenceAvailability::export(&cfg).expect("export ReleaseEvidenceAvailability");
    EvidenceKind::export(&cfg).expect("export EvidenceKind");
    EvidencePin::export(&cfg).expect("export EvidencePin");
    ExecutionPlanContent::export(&cfg).expect("export ExecutionPlanContent");
    MediaAsset::export(&cfg).expect("export MediaAsset");
    ProjectMediaListResponse::export(&cfg).expect("export ProjectMediaListResponse");
    ProjectMediaUploadRequest::export(&cfg).expect("export ProjectMediaUploadRequest");
    ProjectMediaTombstoneRequest::export(&cfg).expect("export ProjectMediaTombstoneRequest");
    MilestoneAcceptanceCheck::export(&cfg).expect("export MilestoneAcceptanceCheck");
    MilestoneAcceptanceCheckState::export(&cfg).expect("export MilestoneAcceptanceCheckState");
    MilestoneDefinitionContent::export(&cfg).expect("export MilestoneDefinitionContent");
    MilestoneDefinitionLifecycle::export(&cfg).expect("export MilestoneDefinitionLifecycle");
    MilestoneDefinitionRevision::export(&cfg).expect("export MilestoneDefinitionRevision");
    MilestoneDefinitionRevisionListResponse::export(&cfg)
        .expect("export MilestoneDefinitionRevisionListResponse");
    ReadinessSnapshotListResponse::export(&cfg).expect("export ReadinessSnapshotListResponse");
    MilestoneLifecycle::export(&cfg).expect("export MilestoneLifecycle");
    MilestoneProjectionReason::export(&cfg).expect("export MilestoneProjectionReason");
    MilestoneProjectionReasonKind::export(&cfg).expect("export MilestoneProjectionReasonKind");
    MutationEnvelope::export(&cfg).expect("export MutationEnvelope");
    OverviewProjectionState::export(&cfg).expect("export OverviewProjectionState");
    PrimaryMilestonePointer::export(&cfg).expect("export PrimaryMilestonePointer");
    PrincipalKind::export(&cfg).expect("export PrincipalKind");
    PrincipalRef::export(&cfg).expect("export PrincipalRef");
    ProductSpecContent::export(&cfg).expect("export ProductSpecContent");
    ProjectCharter::export(&cfg).expect("export ProjectCharter");
    ProjectCharterApproval::export(&cfg).expect("export ProjectCharterApproval");
    ProductAgentSelection::export(&cfg).expect("export ProductAgentSelection");
    ProductGenesisCharterResponse::export(&cfg).expect("export ProductGenesisCharterResponse");
    ProjectCharterContent::export(&cfg).expect("export ProjectCharterContent");
    ProjectCharterReadiness::export(&cfg).expect("export ProjectCharterReadiness");
    ProjectCharterRevision::export(&cfg).expect("export ProjectCharterRevision");
    ProjectCharterState::export(&cfg).expect("export ProjectCharterState");
    ProjectDocument::export(&cfg).expect("export ProjectDocument");
    ProjectDocumentApprovalPolicy::export(&cfg).expect("export ProjectDocumentApprovalPolicy");
    ProjectDocumentListResponse::export(&cfg).expect("export ProjectDocumentListResponse");
    ProjectDocumentApproval::export(&cfg).expect("export ProjectDocumentApproval");
    ProjectDocumentContent::export(&cfg).expect("export ProjectDocumentContent");
    ProjectDocumentKind::export(&cfg).expect("export ProjectDocumentKind");
    ProjectDocumentRevision::export(&cfg).expect("export ProjectDocumentRevision");
    ProjectDocumentRevisionDiffResponse::export(&cfg)
        .expect("export ProjectDocumentRevisionDiffResponse");
    ProjectDocumentRevisionListResponse::export(&cfg)
        .expect("export ProjectDocumentRevisionListResponse");
    ProjectDocumentState::export(&cfg).expect("export ProjectDocumentState");
    ProjectMilestone::export(&cfg).expect("export ProjectMilestone");
    ProjectMilestoneListResponse::export(&cfg).expect("export ProjectMilestoneListResponse");
    ProjectMilestoneOverview::export(&cfg).expect("export ProjectMilestoneOverview");
    ProjectNextAction::export(&cfg).expect("export ProjectNextAction");
    ProjectMode::export(&cfg).expect("export ProjectMode");
    ProjectOverview::export(&cfg).expect("export ProjectOverview");
    PendingDecisionSummary::export(&cfg).expect("export PendingDecisionSummary");
    PendingDecisionAffectedRecords::export(&cfg).expect("export PendingDecisionAffectedRecords");
    PendingDecisionActionTarget::export(&cfg).expect("export PendingDecisionActionTarget");
    PendingDecisionValidity::export(&cfg).expect("export PendingDecisionValidity");
    ProjectRelease::export(&cfg).expect("export ProjectRelease");
    ProjectReleaseListResponse::export(&cfg).expect("export ProjectReleaseListResponse");
    ProvenanceRef::export(&cfg).expect("export ProvenanceRef");
    ProvenanceSourceKind::export(&cfg).expect("export ProvenanceSourceKind");
    AgentChatTopicPrincipalType::export(&cfg).expect("export AgentChatTopicPrincipalType");
    AgentChatTopicResponse::export(&cfg).expect("export AgentChatTopicResponse");
    AgentChatTopicListResponse::export(&cfg).expect("export AgentChatTopicListResponse");
    StartAgentChatTopicRequest::export(&cfg).expect("export StartAgentChatTopicRequest");
    StartAgentChatTopicResponse::export(&cfg).expect("export StartAgentChatTopicResponse");
    ReadinessInput::export(&cfg).expect("export ReadinessInput");
    ReadinessFreshnessStatus::export(&cfg).expect("export ReadinessFreshnessStatus");
    ReadinessFreshness::export(&cfg).expect("export ReadinessFreshness");
    ReadinessReason::export(&cfg).expect("export ReadinessReason");
    ReadinessResult::export(&cfg).expect("export ReadinessResult");
    ReadinessSnapshot::export(&cfg).expect("export ReadinessSnapshot");
    ReleaseDecisionReference::export(&cfg).expect("export ReleaseDecisionReference");
    ReleaseMilestoneRequest::export(&cfg).expect("export ReleaseMilestoneRequest");
    SaveMilestoneRevisionRequest::export(&cfg).expect("export SaveMilestoneRevisionRequest");
    ReleaseSnapshot::export(&cfg).expect("export ReleaseSnapshot");
    ReleaseTaskReference::export(&cfg).expect("export ReleaseTaskReference");
    ReleaseValidationReference::export(&cfg).expect("export ReleaseValidationReference");
    ResearchDocumentContent::export(&cfg).expect("export ResearchDocumentContent");
    ResearchSource::export(&cfg).expect("export ResearchSource");
    RevisionProvenance::export(&cfg).expect("export RevisionProvenance");
    SaveProjectCharterRevisionRequest::export(&cfg)
        .expect("export SaveProjectCharterRevisionRequest");
    SaveProjectDocumentRevisionRequest::export(&cfg)
        .expect("export SaveProjectDocumentRevisionRequest");
    CreateProjectDocumentRequest::export(&cfg).expect("export CreateProjectDocumentRequest");
    CreateDecisionCandidateRequest::export(&cfg).expect("export CreateDecisionCandidateRequest");
    RejectDecisionCandidateRequest::export(&cfg).expect("export RejectDecisionCandidateRequest");
    SetPrimaryMilestoneRequest::export(&cfg).expect("export SetPrimaryMilestoneRequest");
    TransitionMilestoneRevisionRequest::export(&cfg)
        .expect("export TransitionMilestoneRevisionRequest");
    TransitionMilestoneRequest::export(&cfg).expect("export TransitionMilestoneRequest");
    RecordMilestoneCheckRequest::export(&cfg).expect("export RecordMilestoneCheckRequest");
    WaiveMilestoneCheckRequest::export(&cfg).expect("export WaiveMilestoneCheckRequest");
    ReconciliationResolutionAction::export(&cfg).expect("export ReconciliationResolutionAction");
    ReconciliationState::export(&cfg).expect("export ReconciliationState");
    ReconciliationRecordRef::export(&cfg).expect("export ReconciliationRecordRef");
    ReconciliationReplacementRef::export(&cfg).expect("export ReconciliationReplacementRef");
    ReconciliationConflictSummary::export(&cfg).expect("export ReconciliationConflictSummary");
    ReconciliationResolutionSummary::export(&cfg).expect("export ReconciliationResolutionSummary");
    ProjectReconciliation::export(&cfg).expect("export ProjectReconciliation");
    ProjectReconciliationListResponse::export(&cfg)
        .expect("export ProjectReconciliationListResponse");
    ResolveProjectReconciliationRequest::export(&cfg)
        .expect("export ResolveProjectReconciliationRequest");
    ResolveProjectReconciliationResponse::export(&cfg)
        .expect("export ResolveProjectReconciliationResponse");
    TaskProgressCounts::export(&cfg).expect("export TaskProgressCounts");
    ValidationResult::export(&cfg).expect("export ValidationResult");
    VersionedDigest::export(&cfg).expect("export VersionedDigest");
    ProjectAnalyticsResponse::export(&cfg).expect("export ProjectAnalyticsResponse");
    CiStepAnalytics::export(&cfg).expect("export CiStepAnalytics");
    ReviewSummaryAnalytics::export(&cfg).expect("export ReviewSummaryAnalytics");
    AccountUsageAnalyticsResponse::export(&cfg).expect("export AccountUsageAnalyticsResponse");
    MoneyAmount::export(&cfg).expect("export MoneyAmount");
    RateAmount::export(&cfg).expect("export RateAmount");
    TokenCounters::export(&cfg).expect("export TokenCounters");
    RateBuckets::export(&cfg).expect("export RateBuckets");
    CostKind::export(&cfg).expect("export CostKind");
    CostCoverage::export(&cfg).expect("export CostCoverage");
    CostCoverageReasonCode::export(&cfg).expect("export CostCoverageReasonCode");
    CostSourceKind::export(&cfg).expect("export CostSourceKind");
    CostSourceFreshness::export(&cfg).expect("export CostSourceFreshness");
    CostSourceRef::export(&cfg).expect("export CostSourceRef");
    UsageCostCoverage::export(&cfg).expect("export UsageCostCoverage");
    CostCoverageReason::export(&cfg).expect("export CostCoverageReason");
    CostSummary::export(&cfg).expect("export CostSummary");
    UsageAttribution::export(&cfg).expect("export UsageAttribution");
    UsageSurface::export(&cfg).expect("export UsageSurface");
    UsageTelemetryState::export(&cfg).expect("export UsageTelemetryState");
    UsageBreakdown::export(&cfg).expect("export UsageBreakdown");
    ActivityCounts::export(&cfg).expect("export ActivityCounts");
    UsageAggregate::export(&cfg).expect("export UsageAggregate");
    SurfaceUsageBreakdown::export(&cfg).expect("export SurfaceUsageBreakdown");
    ModelUsageBreakdown::export(&cfg).expect("export ModelUsageBreakdown");
    AgentUsageBreakdown::export(&cfg).expect("export AgentUsageBreakdown");
    ProjectUsageBreakdown::export(&cfg).expect("export ProjectUsageBreakdown");
    AnalyticsWindow::export(&cfg).expect("export AnalyticsWindow");
    UsageAnalytics::export(&cfg).expect("export UsageAnalytics");
    OutcomeKind::export(&cfg).expect("export OutcomeKind");
    OutcomeEligibility::export(&cfg).expect("export OutcomeEligibility");
    OutcomeIneligibilityReason::export(&cfg).expect("export OutcomeIneligibilityReason");
    OutcomeCostScope::export(&cfg).expect("export OutcomeCostScope");
    OutcomeCostMetric::export(&cfg).expect("export OutcomeCostMetric");
    PricingCatalogState::export(&cfg).expect("export PricingCatalogState");
    PricingCatalogStatus::export(&cfg).expect("export PricingCatalogStatus");
    PricingCatalogRefreshRequest::export(&cfg).expect("export PricingCatalogRefreshRequest");
    CatalogModelSourceKind::export(&cfg).expect("export CatalogModelSourceKind");
    CatalogModelRate::export(&cfg).expect("export CatalogModelRate");
    PricingCatalogModelsQuery::export(&cfg).expect("export PricingCatalogModelsQuery");
    PricingCatalogModelsResponse::export(&cfg).expect("export PricingCatalogModelsResponse");
    PricingMode::export(&cfg).expect("export PricingMode");
    PricingSettings::export(&cfg).expect("export PricingSettings");
    SubjectPricingResponse::export(&cfg).expect("export SubjectPricingResponse");
    UpdatePricingSettingsRequest::export(&cfg).expect("export UpdatePricingSettingsRequest");
    DeletePricingSettingsQuery::export(&cfg).expect("export DeletePricingSettingsQuery");
    PricingAdjustmentSource::export(&cfg).expect("export PricingAdjustmentSource");
    PricingResolutionStatus::export(&cfg).expect("export PricingResolutionStatus");
    AgentPricing::export(&cfg).expect("export AgentPricing");
    CreateCostEstimationPreviewRequest::export(&cfg)
        .expect("export CreateCostEstimationPreviewRequest");
    CostEstimationPreview::export(&cfg).expect("export CostEstimationPreview");
    CreateCostEstimationRunRequest::export(&cfg).expect("export CreateCostEstimationRunRequest");
    CostEstimationRunStatus::export(&cfg).expect("export CostEstimationRunStatus");
    CostEstimationRun::export(&cfg).expect("export CostEstimationRun");
}
